package tokkoku;
import database.dbtokko;
import support.KartuPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import javax.swing.text.PlainDocument;
import support.NumericFilter;

/**
 *
 * @author Yiung Za
 */
public class Dashboard_owner extends javax.swing.JFrame {
            private int x = 210;
//            JPanel activePanel = null;

    /**
     * Creates new form dbAdmin
     */
    public Dashboard_owner() {
        initComponents();
          btn_penjualan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_pembelian.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_pemasok.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_pengembalian.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_stok.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_laporan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btnRfid.setBackground(new java.awt.Color(255, 255, 255, 0));
//          pnlRfid.setVisible(false);
          menambahRfid.setLocationRelativeTo(null);
          tampilkanPengguna();
          
          
btnCard.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        String kodeRFID = "RF" + (int)(Math.random() * 1000000); // Kode RFID acak
        iptRfid.setText(kodeRFID); // Tampilkan ke textfield

        pnlCard.removeAll(); // Bersihkan panel

        KartuPanel kartu = new KartuPanel("src/gambar/kartu_template.png"); // Sesuaikan path
        kartu.setPreferredSize(new Dimension(pnlCard.getWidth(), pnlCard.getHeight()));
        kartu.setKodeRFID(kodeRFID);

        pnlCard.setLayout(new BorderLayout());
        pnlCard.add(kartu, BorderLayout.CENTER);
        pnlCard.revalidate();
        pnlCard.repaint();
    }
});



btnPrint.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        BufferedImage image = new BufferedImage(pnlCard.getWidth(), pnlCard.getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        pnlCard.paint(g2);
        g2.dispose();

        try {
            ImageIO.write(image, "png", new File("kartu_rfid.png"));
            JOptionPane.showMessageDialog(null, "Kartu berhasil disimpan sebagai kartu_rfid.png");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
});


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menambahRfid = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        iptRfid = new javax.swing.JTextField();
        pnlCard = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnCard = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        dataRPengguna = new javax.swing.JScrollPane();
        tbrPengguna = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnRfid = new javax.swing.JButton();
        btn_penjualan = new javax.swing.JButton();
        btn_pembelian = new javax.swing.JButton();
        btn_pemasok = new javax.swing.JButton();
        btn_pengembalian = new javax.swing.JButton();
        btn_stok = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        backgroundUtama = new javax.swing.JLabel();

        menambahRfid.setTitle("Menambahkan RFID");
        menambahRfid.setBackground(new java.awt.Color(255, 255, 255));
        menambahRfid.setSize(new java.awt.Dimension(800, 600));
        menambahRfid.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setText("Membuat RFID");
        menambahRfid.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        menambahRfid.getContentPane().add(iptRfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 210, 40));

        pnlCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlCard.setForeground(new java.awt.Color(255, 255, 255));
        menambahRfid.getContentPane().add(pnlCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 410, 140));

        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        menambahRfid.getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 110, -1));

        btnCard.setText("Buat Kartu");
        menambahRfid.getContentPane().add(btnCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        btnPrint.setText("Print");
        menambahRfid.getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        tbrPengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama", "RFID"
            }
        ));
        dataRPengguna.setViewportView(tbrPengguna);

        menambahRfid.getContentPane().add(dataRPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 410, 150));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRfid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRfidMouseClicked(evt);
            }
        });
        jPanel1.add(btnRfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 220, 110));

        btn_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseClicked(evt);
            }
        });
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 50));

        btn_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseClicked(evt);
            }
        });
        btn_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembelianActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 50));

        btn_pemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pemasokMouseClicked(evt);
            }
        });
        btn_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pemasokActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 240, 50));

        btn_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseClicked(evt);
            }
        });
        jPanel1.add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 240, 50));

        btn_stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stokMouseClicked(evt);
            }
        });
        btn_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stokActionPerformed(evt);
            }
        });
        jPanel1.add(btn_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 240, 50));

        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 240, 50));

        backgroundUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Pg_dashboard.png"))); // NOI18N
        jPanel1.add(backgroundUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_penjualanActionPerformed

    private void btn_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseClicked
                try {
                    Penjualan_karyawan penjualan = new Penjualan_karyawan();
                    penjualan.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    penjualan.setVisible(true);
                    dispose();
                    System.out.println("Sekarang Page Penjualan");
                } catch (SQLException ex) {
                    Logger.getLogger(Dashboard_owner.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_btn_penjualanMouseClicked

    private void btn_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pembelianActionPerformed

    private void btn_pemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemasokMouseClicked
        // TODO add your handling code here:
            Pemasok_Karyawan pemasok = new Pemasok_Karyawan();
            pemasok.setExtendedState(JFrame.MAXIMIZED_BOTH);
            pemasok.setVisible(true);
            dispose();
            System.out.println("Sekarang Dalam Page Pemasok " + "Master");
    }//GEN-LAST:event_btn_pemasokMouseClicked

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_stokActionPerformed

    private void btn_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseClicked
        // TODO add your handling code here:
            Pembelian_karyawan pembelian = new Pembelian_karyawan();
            pembelian.setExtendedState(JFrame.MAXIMIZED_BOTH);
            pembelian.setVisible(true);
            dispose();
            System.out.println("Sekarang Dalam Page Pembelian " + "Master");
    }//GEN-LAST:event_btn_pembelianMouseClicked

    private void btn_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseClicked
        // TODO add your handling code here:
        System.out.println("Sekarang Dalam Page Pengembalian Barang " + "Master");
    }//GEN-LAST:event_btn_pengembalianMouseClicked

    private void btn_stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stokMouseClicked
        // TODO add your handling code here:
        Menambah_dataBarang stok = new Menambah_dataBarang();
        stok.setExtendedState(JFrame.MAXIMIZED_BOTH);
        stok.setVisible(true);
        dispose();
        System.out.println("Sekarang Dalam Page Stok " + "Master");
    }//GEN-LAST:event_btn_stokMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        Riwayat_karyawan laporan = new Riwayat_karyawan();
        laporan.setExtendedState(JFrame.MAXIMIZED_BOTH);
        laporan.setVisible(true);
        dispose();
        System.out.println("Sekarang Dalam Page Laporan " + "Master");
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btnRfidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRfidMouseClicked
        // TODO add your handling code here:
menambahRfid.setVisible(true);
    }//GEN-LAST:event_btnRfidMouseClicked

    private void btn_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pemasokActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
btnSimpan.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        int baris = tbrPengguna.getSelectedRow();

        if (baris == -1) {
            JOptionPane.showMessageDialog(null, "Pilih dulu baris pengguna pada tabel.");
            return;
        }

        String rfid = iptRfid.getText();
        if (rfid.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode RFID belum tersedia.");
            return;
        }

        // Ambil ID pengguna dari list berdasarkan index baris yang dipilih
        String idPengguna = idPenggunaList.get(baris);

        try {
            Connection conn = dbtokko.configDB();
            String sql = "UPDATE pengguna SET rfid = ? WHERE id_pengguna = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, rfid);
            ps.setString(2, idPengguna);

            int hasil = ps.executeUpdate();

            if (hasil > 0) {
                JOptionPane.showMessageDialog(null, "RFID berhasil disimpan ke pengguna ID: " + idPengguna);
                tampilkanPengguna();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan RFID.");
            }

            ps.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
        }
    }
});
    }//GEN-LAST:event_btnSimpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundUtama;
    private javax.swing.JButton btnCard;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRfid;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_pemasok;
    private javax.swing.JButton btn_pembelian;
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_stok;
    private javax.swing.JScrollPane dataRPengguna;
    private javax.swing.JTextField iptRfid;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDialog menambahRfid;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JTable tbrPengguna;
    // End of variables declaration//GEN-END:variables
private List<String> idPenggunaList = new ArrayList<>();

private void tampilkanPengguna() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nama");
    model.addColumn("RFID");
    idPenggunaList.clear();

    String sql = "SELECT id_pengguna, username, rfid FROM pengguna";

    try {
        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "Tidak ada data pengguna.");
        } else {
            do {
                String idPengguna = rs.getString("id_pengguna");
                String username = rs.getString("username");
                String rfid = rs.getString("rfid");

                idPenggunaList.add(idPengguna);

                model.addRow(new Object[] { username, rfid });
            } while (rs.next());
        }
        tbrPengguna.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}

//private void tampilkanRfid() {
//    // Membuat model tabel dengan kolom yang diinginkan
//    DefaultTableModel model = new DefaultTableModel();
//    model.addColumn("ID Pengguna");
//    model.addColumn("Nama");
//    model.addColumn("Role");
//    model.addColumn("RFID");
//
//    // Query untuk mengambil data pengguna dengan role 'Admin%'
//    String sql = "SELECT id_pengguna, username, role, rfid FROM pengguna WHERE role LIKE 'Admin%'";
//
//    try {
//        Connection conn = dbtokko.configDB(); // Menggunakan koneksi yang sudah tersedia
//        PreparedStatement ps = conn.prepareStatement(sql);
//        ResultSet rs = ps.executeQuery();
//
//        // Cek apakah ada hasil
//        if (!rs.isBeforeFirst()) {
//            JOptionPane.showMessageDialog(this, "Tidak ada pengguna dengan role 'Admin'.");
//        } else {
//            while (rs.next()) {
//                model.addRow(new Object[] {
//                    rs.getString("id_pengguna"),
//                    rs.getString("username"),
//                    rs.getString("role"),
//                    rs.getString("rfid")
//                });
//            }
//        }
//
//        tbrPengguna.setModel(model);
//    } catch (SQLException e) {
//        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
//    }
//}


}


