package tokkoku;
import com.sun.jdi.connect.spi.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import database.dbtokko;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Yiung Za
 */
public class Dashboard_karyawan extends javax.swing.JFrame {
            private int x = 210;
//            JPanel activePanel = null;

    /**
     * Creates new form dbAdmin
     */
    public Dashboard_karyawan() {
        initComponents();
          btn_penjualan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_pembelian.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_pemasok.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_pengembalian.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_stok.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_laporan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_logout.setBackground(new java.awt.Color(255, 255, 255, 0));

//          pnlRfid.setVisible(false);
//          menambahRfid.setLocationRelativeTo(null);
//          tampilkanPengguna();
          
          
//btnCard.addActionListener(new ActionListener() {
//    @Override
//    public void actionPerformed(ActionEvent e) {
//        String kodeRFID = "RF" + (int)(Math.random() * 1000000); // Kode RFID acak
//        iptRfid.setText(kodeRFID); // Tampilkan ke textfield
//
//        pnlCard.removeAll(); // Bersihkan panel
//
//        KartuPanel kartu = new KartuPanel("src/gambar/kartu_template.png"); // Sesuaikan path
//        kartu.setPreferredSize(new Dimension(pnlCard.getWidth(), pnlCard.getHeight()));
//        kartu.setKodeRFID(kodeRFID);
//
//        pnlCard.setLayout(new BorderLayout());
//        pnlCard.add(kartu, BorderLayout.CENTER);
//        pnlCard.revalidate();
//        pnlCard.repaint();
//    }
//});



//btnPrint.addActionListener(new ActionListener() {
//    @Override
//    public void actionPerformed(ActionEvent e) {
//        BufferedImage image = new BufferedImage(pnlCard.getWidth(), pnlCard.getHeight(), BufferedImage.TYPE_INT_RGB);
//        Graphics2D g2 = image.createGraphics();
//        pnlCard.paint(g2);
//        g2.dispose();
//
//        try {
//            ImageIO.write(image, "png", new File("kartu_rfid.png"));
//            JOptionPane.showMessageDialog(null, "Kartu berhasil disimpan sebagai kartu_rfid.png");
//        } catch (IOException ex) {
//            ex.printStackTrace();
//        }
//    }
//});


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_penjualan = new javax.swing.JButton();
        btn_pembelian = new javax.swing.JButton();
        btn_pemasok = new javax.swing.JButton();
        btn_pengembalian = new javax.swing.JButton();
        btn_stok = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        show_totalBarangDikembalikan = new javax.swing.JButton();
        show_totalStok = new javax.swing.JButton();
        show_totalBarangRusak = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        backgroundUtama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseClicked(evt);
            }
        });
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 50));

        btn_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseClicked(evt);
            }
        });
        btn_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembelianActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 50));

        btn_pemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pemasokMouseClicked(evt);
            }
        });
        btn_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pemasokActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 240, 50));

        btn_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseClicked(evt);
            }
        });
        jPanel1.add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 240, 50));

        btn_stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stokMouseClicked(evt);
            }
        });
        btn_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stokActionPerformed(evt);
            }
        });
        jPanel1.add(btn_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 240, 50));

        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 240, 50));

        show_totalBarangDikembalikan.setBackground(new java.awt.Color(153, 51, 255));
        show_totalBarangDikembalikan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        show_totalBarangDikembalikan.setForeground(new java.awt.Color(255, 255, 255));
        show_totalBarangDikembalikan.setText("Lihat Barang Dikembalikan");
        show_totalBarangDikembalikan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        show_totalBarangDikembalikan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_totalBarangDikembalikanMouseClicked(evt);
            }
        });
        show_totalBarangDikembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_totalBarangDikembalikanActionPerformed(evt);
            }
        });
        jPanel1.add(show_totalBarangDikembalikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 200, 120));

        show_totalStok.setBackground(new java.awt.Color(0, 0, 255));
        show_totalStok.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        show_totalStok.setForeground(new java.awt.Color(255, 255, 255));
        show_totalStok.setText("Lihat Stok");
        show_totalStok.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        show_totalStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_totalStokMouseClicked(evt);
            }
        });
        show_totalStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_totalStokActionPerformed(evt);
            }
        });
        jPanel1.add(show_totalStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 200, 120));

        show_totalBarangRusak.setBackground(new java.awt.Color(255, 51, 51));
        show_totalBarangRusak.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        show_totalBarangRusak.setForeground(new java.awt.Color(255, 255, 255));
        show_totalBarangRusak.setText("Lihat Barang Rusak");
        show_totalBarangRusak.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        show_totalBarangRusak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_totalBarangRusakMouseClicked(evt);
            }
        });
        show_totalBarangRusak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_totalBarangRusakActionPerformed(evt);
            }
        });
        jPanel1.add(show_totalBarangRusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 200, 120));

        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 240, 50));

        backgroundUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Pg_Desktop-Karyawan.png"))); // NOI18N
        jPanel1.add(backgroundUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_penjualanActionPerformed

    private void btn_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseClicked
                try {
                    Penjualan_karyawan penjualan = new Penjualan_karyawan();
                    penjualan.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    penjualan.setVisible(true);
                    dispose();
                    System.out.println("Sekarang Dalam Page Penjualan");
                } catch (SQLException ex) {
                    Logger.getLogger(Dashboard_karyawan.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_btn_penjualanMouseClicked

    private void btn_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pembelianActionPerformed

    private void btn_pemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemasokMouseClicked
        // TODO add your handling code here:
            Pemasok_Karyawan pemasok = new Pemasok_Karyawan();
            pemasok.setExtendedState(JFrame.MAXIMIZED_BOTH);
            pemasok.setVisible(true);
            dispose();
            System.out.println("Sekarang Dalam Page Pemasok");
    }//GEN-LAST:event_btn_pemasokMouseClicked

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_stokActionPerformed

    private void btn_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseClicked
        // TODO add your handling code here:
            Pembelian_karyawan pembelian = new Pembelian_karyawan();
            pembelian.setExtendedState(JFrame.MAXIMIZED_BOTH);
            pembelian.setVisible(true);
            dispose();
            System.out.println("Sekarang Dalam Page Pembelian");
    }//GEN-LAST:event_btn_pembelianMouseClicked

    private void btn_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseClicked
        // TODO add your handling code here:
        PengembalianBarang_karyawan pengembalian = new PengembalianBarang_karyawan();
        pengembalian.setExtendedState(JFrame.MAXIMIZED_BOTH);
        pengembalian.setVisible(true);
        dispose();
        System.out.println("Sekarang Dalam Page Pengembalian Barang");
    }//GEN-LAST:event_btn_pengembalianMouseClicked

    private void btn_stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stokMouseClicked
        // TODO add your handling code here:
        Menambah_dataBarang stok = new Menambah_dataBarang();
        stok.setExtendedState(JFrame.MAXIMIZED_BOTH);
        stok.setVisible(true);
        dispose();
        System.out.println("Sekarang Dalam Page Stok");
    }//GEN-LAST:event_btn_stokMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        Riwayat_karyawan laporan = new Riwayat_karyawan();
        laporan.setExtendedState(JFrame.MAXIMIZED_BOTH);
        laporan.setVisible(true);
        dispose();
        System.out.println("Sekarang Dalam Page Riwayat");
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pemasokActionPerformed

    private void show_totalBarangDikembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_totalBarangDikembalikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_totalBarangDikembalikanActionPerformed

    private void show_totalStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_totalStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_totalStokActionPerformed

    private void show_totalBarangRusakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_totalBarangRusakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_totalBarangRusakActionPerformed

    private void show_totalStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_totalStokMouseClicked
 String sql = "SELECT SUM(stok) AS total_stok FROM stok_produk";

    try (
        java.sql.Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery()
    ) {
        if (rs.next()) {
            int totalStok = rs.getInt("total_stok");
            // Set tulisan pada tombol menjadi total stok
            show_totalStok.setText("Total Stok: " + totalStok);
        } else {
            show_totalStok.setText("Stok: 0");
        }
    } catch (SQLException ex) {
        show_totalStok.setText("Error");
        System.err.println("SQL Error: " + ex.getMessage());
    }

    }//GEN-LAST:event_show_totalStokMouseClicked

    private void show_totalBarangRusakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_totalBarangRusakMouseClicked
        // TODO add your handling code here:
 String sql = "SELECT SUM(jumlah) AS total_rusak FROM barang_rusak";

    try (
        java.sql.Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery()
    ) {
        if (rs.next()) {
            int totalRusak = rs.getInt("total_rusak");
            // Set tulisan pada tombol menjadi total stok
            show_totalBarangRusak.setText("Total Rusak: " + totalRusak);
        } else {
            show_totalBarangRusak.setText("Rusak: 0");
        }
    } catch (SQLException ex) {
        show_totalBarangRusak.setText("Error");
        System.err.println("SQL Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_show_totalBarangRusakMouseClicked

    private void show_totalBarangDikembalikanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_totalBarangDikembalikanMouseClicked
        // TODO add your handling code here:
 String sql = "SELECT SUM(jumlah) AS total_kembalikan FROM return_pembelian";

    try (
        java.sql.Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery()
    ) {
        if (rs.next()) {
            int totalKembalikan = rs.getInt("total_kembalikan");
            // Set tulisan pada tombol menjadi total stok
            show_totalBarangDikembalikan.setText("Total Dikembalikan: " + totalKembalikan);
        } else {
            show_totalBarangDikembalikan.setText("Dikembalikan: 0");
        }
    } catch (SQLException ex) {
        show_totalBarangDikembalikan.setText("Error");
        System.err.println("SQL Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_show_totalBarangDikembalikanMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
    int confirm = JOptionPane.showConfirmDialog(
    null,
    "Yakin ingin logout?",
    "Konfirmasi Logout",
    JOptionPane.YES_NO_OPTION
);

if (confirm == JOptionPane.YES_OPTION) {
    Login login = new Login();
    login.setExtendedState(JFrame.MAXIMIZED_BOTH);
    login.setVisible(true);
    dispose();
    System.out.println("Anda Logout");
} else {
    System.out.println("Logout dibatalkan");
}

    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundUtama;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pemasok;
    private javax.swing.JButton btn_pembelian;
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_stok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton show_totalBarangDikembalikan;
    private javax.swing.JButton show_totalBarangRusak;
    private javax.swing.JButton show_totalStok;
    // End of variables declaration//GEN-END:variables
//private List<String> idPenggunaList = new ArrayList<>();
//
//private void tampilkanPengguna() {
//    DefaultTableModel model = new DefaultTableModel();
//    model.addColumn("Nama");
//    model.addColumn("RFID");
//    idPenggunaList.clear();
//
//    String sql = "SELECT id_pengguna, username, rfid FROM pengguna";
//
//    try {
//        Connection conn = dbtokko.configDB();
//        PreparedStatement ps = conn.prepareStatement(sql);
//        ResultSet rs = ps.executeQuery();
//
//        if (!rs.next()) {
//            JOptionPane.showMessageDialog(this, "Tidak ada data pengguna.");
//        } else {
//            do {
//                String idPengguna = rs.getString("id_pengguna");
//                String username = rs.getString("username");
//                String rfid = rs.getString("rfid");
//
//                idPenggunaList.add(idPengguna);
//
//                model.addRow(new Object[] { username, rfid });
//            } while (rs.next());
//        }
//        tbrPengguna.setModel(model);
//    } catch (SQLException e) {
//        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
//    }
//}




}


