/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokkoku;
import com.lowagie.text.pdf.PdfWriter;
import database.dbtokko;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import com.itextpdf.text.DocumentException;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Element;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.pdf.PdfPTable;

import javax.swing.*;
import javax.swing.table.TableModel;
import java.io.File;
import java.io.FileOutputStream;
import java.util.Date;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;




/**
 *
 * @author Yiung Za
 */
public class Laporan_Owner extends javax.swing.JFrame {

    public Laporan_Owner() {
        initComponents();
          btn_penjualan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_dashboard.setBackground(new java.awt.Color(255, 255, 255, 0));
          pencarian.setBackground(new java.awt.Color(255, 255, 255, 0));
          
          tampilkanDataPenjualan(false, null, null);
          tampilkanDataPembelian(false, null, null);
          tampilkanDataBarangRusak(false, null, null);
          tampilkanDataReturn(false, null, null);
          pembelianTbl.setVisible(false);
          barangRusakTbl.setVisible(false);
          pengembalianTbl.setVisible(false);
          
//JcomboBox Report
Claporan.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        String selected = (String) Claporan.getSelectedItem();
        System.out.println("Selected: " + selected);

        penjualanTbl.setVisible(false);
        pembelianTbl.setVisible(false);
        barangRusakTbl.setVisible(false);
        pengembalianTbl.setVisible(false);
        if ("Laporan Penjualan".equals(selected)) {
            penjualanTbl.setVisible(true);
        } else if ("Laporan Pembelian".equals(selected)) {
          pembelianTbl.setVisible(true);
        } else if ("Laporan Barang Rusak".equals(selected)) {
            barangRusakTbl.setVisible(true);
        } else if ("Laporan Barang Dikembalikan".equals(selected)) {
            pengembalianTbl.setVisible(true);
        }

        revalidate();
        repaint();
    }
});

pencarian.getDocument().addDocumentListener(new DocumentListener() {
    public void insertUpdate(DocumentEvent e) { cari(); }
    public void removeUpdate(DocumentEvent e) { cari(); }
    public void changedUpdate(DocumentEvent e) { cari(); }

    private void cari() {
        String keyword = pencarian.getText().trim();
        tampilkanDataPenjualanDenganPencarian(keyword);
        tampilkanDataPembelianDenganPencarian(keyword);
        tampilkanDataBarangRusakDenganPencarian(keyword);
        tampilkanDataReturnDenganPencarian(keyword);
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Claporan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn_penjualan = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();
        pengembalianTbl = new javax.swing.JScrollPane();
        pengembalian = new javax.swing.JTable();
        barangRusakTbl = new javax.swing.JScrollPane();
        barangRusak = new javax.swing.JTable();
        penjualanTbl = new javax.swing.JScrollPane();
        penjualan = new javax.swing.JTable();
        Jsampai = new de.wannawork.jcalendar.JCalendarComboBox();
        Jdari = new de.wannawork.jcalendar.JCalendarComboBox();
        Tampilkan = new javax.swing.JButton();
        pembelianTbl = new javax.swing.JScrollPane();
        pembelian = new javax.swing.JTable();
        Jkerugian = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        show_kerugian = new javax.swing.JTextField();
        show_keuntungan = new javax.swing.JTextField();
        btn_segarkan = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        show_totalTransaksi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        show_selisih = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pencarian = new javax.swing.JTextField();
        show_totalPembelian = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        backgroundUtama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Claporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laporan Penjualan", "Laporan Pembelian", "Laporan Barang Rusak", "Laporan Barang Dikembalikan"}));
        jPanel1.add(Claporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 220, 50));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("S/d");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 30, -1));

        btn_penjualan.setBorder(null);
        btn_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseClicked(evt);
            }
        });
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 60));

        btn_dashboard.setBorder(null);
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
        });
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 50));

        pengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pengembalian", "Kode Pembelian", "Kode Produk", "Jumlah", "Alasan", "Tanggal Pengembalian"
            }
        ));
        pengembalianTbl.setViewportView(pengembalian);

        jPanel1.add(pengembalianTbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 1060, 310));

        barangRusak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Rusak", "Kode Produk", "Jumlah", "Alasan", "Tanggal Rusak"
            }
        ));
        barangRusakTbl.setViewportView(barangRusak);

        jPanel1.add(barangRusakTbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 1060, 310));

        penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Penjualan", "Kasir", "ID Produk", "Produk", "Barcode", "Harga", "Jumlah", "Subtotal", "Tanggal Transaksi"
            }
        ));
        penjualanTbl.setViewportView(penjualan);

        jPanel1.add(penjualanTbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 1060, 310));
        jPanel1.add(Jsampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 130, 30));
        jPanel1.add(Jdari, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 130, 30));

        Tampilkan.setText("Tampilkan");
        Tampilkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TampilkanMouseClicked(evt);
            }
        });
        jPanel1.add(Tampilkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, -1, -1));

        pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pembelian", "Nama Kasir", "ID Produk", "Nama Produk", "Jumlah", "Harga Beli", "Subtotal", "Tanggal Transaksi"
            }
        ));
        pembelianTbl.setViewportView(pembelian);

        jPanel1.add(pembelianTbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 1060, 310));

        Jkerugian.setForeground(new java.awt.Color(0, 0, 0));
        Jkerugian.setText("Kerugian");
        jPanel1.add(Jkerugian, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Selisih");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, -1, -1));
        jPanel1.add(show_kerugian, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 150, 30));
        jPanel1.add(show_keuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, 150, 30));

        btn_segarkan.setText("Segarkan");
        btn_segarkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_segarkanMouseClicked(evt);
            }
        });
        jPanel1.add(btn_segarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, -1, -1));

        btn_print.setText("Cetak");
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
        });
        jPanel1.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, -1, -1));
        jPanel1.add(show_totalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 150, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Keuntungan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, -1, -1));
        jPanel1.add(show_selisih, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 150, 30));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total Pembelian");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, -1));

        pencarian.setBorder(null);
        jPanel1.add(pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 99, 140, 30));

        show_totalPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_totalPembelianActionPerformed(evt);
            }
        });
        jPanel1.add(show_totalPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 130, 30));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Total Penjualan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 240, 50));

        backgroundUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Pg_Laporan-Owner.png"))); // NOI18N
        jPanel1.add(backgroundUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_penjualanActionPerformed

    private void btn_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseClicked
        // TODO add your handling code here:
    Manajemen_karyawan_Owner manajemen = new Manajemen_karyawan_Owner();
    manajemen.setExtendedState(JFrame.MAXIMIZED_BOTH);
    manajemen.setVisible(true);
    dispose();
    System.out.println("Sekarang Berada Di Page Manajemen Karyawan");
    }//GEN-LAST:event_btn_penjualanMouseClicked

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        // TODO add your handling code here:
    Dashboard_owner dashboard = new Dashboard_owner();
    dashboard.setExtendedState(JFrame.MAXIMIZED_BOTH);
    dashboard.setVisible(true);
    dispose();
    System.out.println("Sekarang Berada Di Page Dashboard");
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void TampilkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TampilkanMouseClicked
        // TODO add your handling code here:
java.util.Date dariDate = Jdari.getDate();
java.util.Date sampaiDate = Jsampai.getDate();

boolean filterTanggal = !(dariDate == null || sampaiDate == null);


tampilkanDataPenjualan(filterTanggal, dariDate, sampaiDate);
tampilkanDataPembelian(filterTanggal, dariDate, sampaiDate);
tampilkanDataReturn(filterTanggal, dariDate, sampaiDate);

hitungRingkasanTransaksi(filterTanggal, dariDate, sampaiDate);
    }//GEN-LAST:event_TampilkanMouseClicked

    private void btn_segarkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_segarkanMouseClicked
        // TODO add your handling code here:
    tampilkanDataPenjualan(false, null, null);
    tampilkanDataPembelian(false, null, null);
    tampilkanDataReturn(false, null, null);
    show_selisih.setText("");
    show_keuntungan.setText("");
    show_kerugian.setText("");
    show_totalTransaksi.setText("");
    }//GEN-LAST:event_btn_segarkanMouseClicked

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan PDF");
        fileChooser.setSelectedFile(new File("laporan-transaksi.pdf"));

        int userSelection = fileChooser.showSaveDialog(null);
        if (userSelection ==  JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            exportPDF(fileToSave);
        }

    }//GEN-LAST:event_btn_printMouseClicked

    private void show_totalPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_totalPembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_totalPembelianActionPerformed

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            null,
            "Yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setExtendedState(JFrame.MAXIMIZED_BOTH);
            login.setVisible(true);
            dispose();
            System.out.println("Anda Logout");
        } else {
            System.out.println("Logout dibatalkan");
        }
    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan_Owner().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Claporan;
    private de.wannawork.jcalendar.JCalendarComboBox Jdari;
    private javax.swing.JLabel Jkerugian;
    private de.wannawork.jcalendar.JCalendarComboBox Jsampai;
    private javax.swing.JButton Tampilkan;
    private javax.swing.JLabel backgroundUtama;
    private javax.swing.JTable barangRusak;
    private javax.swing.JScrollPane barangRusakTbl;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_segarkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable pembelian;
    private javax.swing.JScrollPane pembelianTbl;
    private javax.swing.JTextField pencarian;
    private javax.swing.JTable pengembalian;
    private javax.swing.JScrollPane pengembalianTbl;
    private javax.swing.JTable penjualan;
    private javax.swing.JScrollPane penjualanTbl;
    private javax.swing.JTextField show_kerugian;
    private javax.swing.JTextField show_keuntungan;
    private javax.swing.JTextField show_selisih;
    private javax.swing.JTextField show_totalPembelian;
    private javax.swing.JTextField show_totalTransaksi;
    // End of variables declaration//GEN-END:variables

private void hitungRingkasanTransaksi(boolean filterTanggal, java.util.Date dariDate, java.util.Date sampaiDate) {
    double totalPenjualan = 0;
    double totalPembelian = 0;
    double totalHargaBeliTerjual = 0;
    double totalKerugian = 0;

    SimpleDateFormat sdfSQL = new SimpleDateFormat("yyyy-MM-dd");

    try {
        Connection conn = dbtokko.configDB();

        // Hitung total penjualan
        String sqlPenjualan = "SELECT SUM(dp.subtotal) AS total_penjualan " +
                              "FROM penjualan p " +
                              "JOIN detail_penjualan dp ON p.id_penjualan = dp.id_penjualan";
        if (filterTanggal) {
            sqlPenjualan += " WHERE DATE(p.tanggal_transaksi) BETWEEN ? AND ?";
        }

        PreparedStatement psPenjualan = conn.prepareStatement(sqlPenjualan);
        if (filterTanggal) {
            psPenjualan.setString(1, sdfSQL.format(dariDate));
            psPenjualan.setString(2, sdfSQL.format(sampaiDate));
        }
        ResultSet rsPenjualan = psPenjualan.executeQuery();
        if (rsPenjualan.next()) {
            totalPenjualan = rsPenjualan.getDouble("total_penjualan");
        }
        rsPenjualan.close();
        psPenjualan.close();

        // Hitung total pembelian (semua)
        String sqlPembelian = "SELECT SUM(dp.subtotal) AS total_pembelian " +
                              "FROM pembelian p " +
                              "JOIN detail_pembelian dp ON p.id_pembelian = dp.id_pembelian";
        if (filterTanggal) {
            sqlPembelian += " WHERE DATE(p.tanggal_pembelian) BETWEEN ? AND ?";
        }

        PreparedStatement psPembelian = conn.prepareStatement(sqlPembelian);
        if (filterTanggal) {
            psPembelian.setString(1, sdfSQL.format(dariDate));
            psPembelian.setString(2, sdfSQL.format(sampaiDate));
        }
        ResultSet rsPembelian = psPembelian.executeQuery();
        if (rsPembelian.next()) {
            totalPembelian = rsPembelian.getDouble("total_pembelian");
        }
        rsPembelian.close();
        psPembelian.close();

        // Hitung total harga beli dari barang yang terjual
        String sqlHargaBeliTerjual = "SELECT dp.jumlah, dp.harga_beli " +
                                     "FROM detail_penjualan dp " +
                                     "JOIN penjualan p ON p.id_penjualan = dp.id_penjualan";
        if (filterTanggal) {
            sqlHargaBeliTerjual += " WHERE DATE(p.tanggal_transaksi) BETWEEN ? AND ?";
        }

        PreparedStatement psHargaBeli = conn.prepareStatement(sqlHargaBeliTerjual);
        if (filterTanggal) {
            psHargaBeli.setString(1, sdfSQL.format(dariDate));
            psHargaBeli.setString(2, sdfSQL.format(sampaiDate));
        }
        ResultSet rsHargaBeli = psHargaBeli.executeQuery();
        while (rsHargaBeli.next()) {
            int jumlah = rsHargaBeli.getInt("jumlah");
            double hargaBeli = rsHargaBeli.getDouble("harga_beli");
            totalHargaBeliTerjual += jumlah * hargaBeli;
        }
        rsHargaBeli.close();
        psHargaBeli.close();

        // Hitung total kerugian dari barang rusak
        String sqlBarangRusak = "SELECT br.jumlah, sp.harga_beli " +
                                "FROM barang_rusak br " +
                                "JOIN stok_produk sp ON br.id_produk = sp.id_produk";
        if (filterTanggal) {
            sqlBarangRusak += " WHERE DATE(br.tanggal_rusak) BETWEEN ? AND ?";
        }

        PreparedStatement psRusak = conn.prepareStatement(sqlBarangRusak);
        if (filterTanggal) {
            psRusak.setString(1, sdfSQL.format(dariDate));
            psRusak.setString(2, sdfSQL.format(sampaiDate));
        }
        ResultSet rsRusak = psRusak.executeQuery();
        while (rsRusak.next()) {
            int jumlah = rsRusak.getInt("jumlah");
            double hargaBeli = rsRusak.getDouble("harga_beli");
            totalKerugian += jumlah * hargaBeli;
        }
        rsRusak.close();
        psRusak.close();

        double selisih = totalPenjualan - totalHargaBeliTerjual;
        double keuntunganBersih = selisih - totalKerugian;

        show_totalTransaksi.setText(String.format("Rp %.2f", totalPenjualan));
        show_totalPembelian.setText(String.format("Rp %.2f", totalPembelian));
        show_keuntungan.setText(String.format("Rp %.2f", Math.max(keuntunganBersih, 0)));
        show_kerugian.setText(String.format("Rp %.2f", totalKerugian));
        show_selisih.setText(String.format("Rp %.2f", selisih));

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menghitung ringkasan transaksi: " + e.getMessage());
    }
}






    
    
    
    
    
    
    
    
    
    
    
    
    private void tampilkanDataPenjualan(boolean filterTanggal, java.util.Date dariDate, java.util.Date sampaiDate) {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "ID Penjualan", "Kasir", "ID Produk", "Nama Produk", "Barcode", "Harga", "Jumlah", "Subtotal", "Tanggal Transaksi"
    });

    try {
        SimpleDateFormat sdfSQL = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdfTampil = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String sql = "SELECT p.id_penjualan, u.username, pr.id_produk, pr.nama_produk, pr.barcode, " +
                     "dp.harga_jual, dp.jumlah, dp.subtotal, p.tanggal_transaksi " +
                     "FROM penjualan p " +
                     "JOIN pengguna u ON p.id_pengguna = u.id_pengguna " +
                     "JOIN detail_penjualan dp ON p.id_penjualan = dp.id_penjualan " +
                     "JOIN produk pr ON dp.id_produk = pr.id_produk";

        if (filterTanggal) {
            sql += " WHERE DATE(p.tanggal_transaksi) BETWEEN ? AND ?";
        }

        sql += " ORDER BY p.tanggal_transaksi ASC";

        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);

        if (filterTanggal) {
            ps.setString(1, sdfSQL.format(dariDate));
            ps.setString(2, sdfSQL.format(sampaiDate));
        }

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("id_penjualan"),
                rs.getString("username"),
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getString("barcode"),
                rs.getDouble("harga_jual"),
                rs.getInt("jumlah"),
                rs.getDouble("subtotal"),
                sdfTampil.format(rs.getTimestamp("tanggal_transaksi"))
            };
            model.addRow(row);
        }

        penjualan.setModel(model);
        sesuaikanLebarKolom(penjualan);

        rs.close();
        ps.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data: " + e.getMessage());
    }
}

private void tampilkanDataPembelian(boolean filterTanggal, java.util.Date dariDate, java.util.Date sampaiDate) {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "ID Pembelian", "Nama Kasir", "ID Produk", "Nama Produk", "Jumlah", "Harga Beli", "Subtotal", "Tanggal Pembelian"
    });

    try {
        SimpleDateFormat sdfSQL = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdfTampil = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String sql = "SELECT p.id_pembelian, u.username, pr.id_produk, pr.nama_produk, " +
                     "dp.jumlah, dp.harga_beli, dp.subtotal, p.tanggal_pembelian " +
                     "FROM pembelian p " +
                     "JOIN pengguna u ON p.id_pengguna = u.id_pengguna " +
                     "JOIN detail_pembelian dp ON p.id_pembelian = dp.id_pembelian " +
                     "JOIN produk pr ON dp.id_produk = pr.id_produk";

        if (filterTanggal) {
            sql += " WHERE DATE(p.tanggal_pembelian) BETWEEN ? AND ?";
        }

        sql += " ORDER BY p.tanggal_pembelian ASC";

        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);

        if (filterTanggal) {
            ps.setString(1, sdfSQL.format(dariDate));
            ps.setString(2, sdfSQL.format(sampaiDate));
        }

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("id_pembelian"),
                rs.getString("username"),
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getInt("jumlah"),
                rs.getDouble("harga_beli"),
                rs.getDouble("subtotal"),
                sdfTampil.format(rs.getTimestamp("tanggal_pembelian"))
            };
            model.addRow(row);
        }

        pembelian.setModel(model);
        sesuaikanLebarKolom(pembelian);

        rs.close();
        ps.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data pembelian: " + e.getMessage());
    }
}

private void tampilkanDataBarangRusak(boolean filterTanggal, java.util.Date dariDate, java.util.Date sampaiDate) {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "ID Rusak", "ID Produk", "Nama Produk", "Jumlah", "Alasan", "Tanggal Rusak"
    });

    try {
        SimpleDateFormat sdfSQL = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdfTampil = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String sql = "SELECT br.id_rusak, br.id_produk, pr.nama_produk, br.jumlah, br.alasan, br.tanggal_rusak " +
                     "FROM barang_rusak br " +
                     "JOIN produk pr ON br.id_produk = pr.id_produk";

        if (filterTanggal) {
            sql += " WHERE DATE(br.tanggal_rusak) BETWEEN ? AND ?";
        }

        sql += " ORDER BY br.tanggal_rusak ASC";

        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);

        if (filterTanggal) {
            ps.setString(1, sdfSQL.format(dariDate));
            ps.setString(2, sdfSQL.format(sampaiDate));
        }

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("id_rusak"),
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getInt("jumlah"),
                rs.getString("alasan"),
                sdfTampil.format(rs.getTimestamp("tanggal_rusak"))
            };
            model.addRow(row);
        }

        barangRusak.setModel(model);
        sesuaikanLebarKolom(barangRusak);

        rs.close();
        ps.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data barang rusak: " + e.getMessage());
    }
}

private void tampilkanDataReturn(boolean filterTanggal, java.util.Date dariDate, java.util.Date sampaiDate) {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "ID Return", "ID Pembelian", "ID Produk", "Nama Produk", "Jumlah", "Alasan", "Tanggal Return"
    });

    try {
        SimpleDateFormat sdfSQL = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdfTampil = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String sql = "SELECT r.id_retur, r.id_pembelian, r.id_produk, p.nama_produk, " +
                     "r.jumlah, r.alasan, r.tanggal_return " +
                     "FROM return_pembelian r " +
                     "JOIN produk p ON r.id_produk = p.id_produk";

        if (filterTanggal) {
            sql += " WHERE DATE(r.tanggal_return) BETWEEN ? AND ?";
        }

        sql += " ORDER BY r.tanggal_return ASC";

        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);

        if (filterTanggal) {
            ps.setString(1, sdfSQL.format(dariDate));
            ps.setString(2, sdfSQL.format(sampaiDate));
        }

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("id_retur"),
                rs.getString("id_pembelian"),
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getInt("jumlah"),
                rs.getString("alasan"),
                sdfTampil.format(rs.getTimestamp("tanggal_return"))
            };
            model.addRow(row);
        }

        pengembalian.setModel(model);
        sesuaikanLebarKolom(pengembalian);

        rs.close();
        ps.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data return: " + e.getMessage());
    }
}


























private void sesuaikanLebarKolom(JTable table) {
    final TableColumnModel columnModel = table.getColumnModel();
    for (int column = 0; column < table.getColumnCount(); column++) {
        int lebar = 15;
        for (int row = 0; row < table.getRowCount(); row++) {
            TableCellRenderer renderer = table.getCellRenderer(row, column);
            Component comp = table.prepareRenderer(renderer, row, column);
            lebar = Math.max(comp.getPreferredSize().width + 10, lebar);
        }
        if (lebar > 300)
            lebar = 300;
        columnModel.getColumn(column).setPreferredWidth(lebar);
    }
}


    private void tampilkanDataPenjualan() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
public void exportPDF(File file) {
    Document documentPDF = new Document(PageSize.A4.rotate());
    try {
        PdfWriter.getInstance(documentPDF, new FileOutputStream(file));
        documentPDF.open();

        Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD);
        Font subFont = new Font(Font.HELVETICA, 12, Font.NORMAL);
        Font boldFont = new Font(Font.HELVETICA, 12, Font.BOLD);

        Paragraph toko = new Paragraph("Toko Amanah", titleFont);
        toko.setAlignment(Element.ALIGN_CENTER);
        documentPDF.add(toko);

        String tanggalCetak = new SimpleDateFormat("dd MMMM yyyy").format(new Date());
        Paragraph tanggal = new Paragraph("Tanggal Cetak: " + tanggalCetak, subFont);
        tanggal.setAlignment(Element.ALIGN_RIGHT);
        documentPDF.add(tanggal);

        documentPDF.add(new Paragraph(" "));

        Paragraph title = new Paragraph("LAPORAN PENJUALAN, PEMBELIAN, BARANG RUSAK, DAN RETURN PEMBELIAN", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        documentPDF.add(title);

        documentPDF.add(new Paragraph(" "));

        documentPDF.add(new Paragraph("Ringkasan Laporan:", boldFont));
        documentPDF.add(new Paragraph("Total Transaksi : " + show_totalTransaksi.getText(), subFont));
        documentPDF.add(new Paragraph("Keuntungan      : " + show_keuntungan.getText(), subFont));
        documentPDF.add(new Paragraph("Kerugian        : " + show_kerugian.getText(), subFont));
        documentPDF.add(new Paragraph("Selisih         : " + show_selisih.getText(), subFont));

        documentPDF.add(new Paragraph(" "));

        Paragraph p1 = new Paragraph("Tabel Penjualan", boldFont);
        p1.setAlignment(Element.ALIGN_LEFT);
        documentPDF.add(p1);
        PdfPTable tablePenjualan = createPdfTableFromJTable(penjualan);
        documentPDF.add(tablePenjualan);

        documentPDF.add(new Paragraph(" "));

        Paragraph p2 = new Paragraph("Tabel Pembelian", boldFont);
        p2.setAlignment(Element.ALIGN_LEFT);
        documentPDF.add(p2);
        PdfPTable tablePembelian = createPdfTableFromJTable(pembelian);
        documentPDF.add(tablePembelian);

        documentPDF.add(new Paragraph(" "));

        Paragraph p3 = new Paragraph("Tabel Barang Rusak", boldFont);
        p3.setAlignment(Element.ALIGN_LEFT);
        documentPDF.add(p3);
        PdfPTable tableBarangRusak = createPdfTableFromJTable(barangRusak);
        documentPDF.add(tableBarangRusak);

        documentPDF.add(new Paragraph(" "));

        Paragraph p4 = new Paragraph("Tabel Pengembalian Pembelian", boldFont);
        p4.setAlignment(Element.ALIGN_LEFT);
        documentPDF.add(p4);
        PdfPTable tableReturn = createPdfTableFromJTable(pengembalian);
        documentPDF.add(tableReturn);

        documentPDF.close();
        JOptionPane.showMessageDialog(null, "PDF berhasil disimpan!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal export PDF: " + e.getMessage());
    }
}


    
    
public PdfPTable createPdfTableFromJTable(JTable table) {
    TableModel model = table.getModel();
    PdfPTable pdfTable = new PdfPTable(model.getColumnCount());

    for (int i = 0; i < model.getColumnCount(); i++) {
        pdfTable.addCell(model.getColumnName(i));
    }

    for (int rows = 0; rows < model.getRowCount(); rows++) {
        for (int cols = 0; cols < model.getColumnCount(); cols++) {
            Object value = model.getValueAt(rows, cols);
            pdfTable.addCell(value != null ? value.toString() : "");
        }
    }

    return pdfTable;
}



private void tampilkanDataPenjualanDenganPencarian(String keyword) {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "ID Penjualan", "Kasir", "ID Produk", "Nama Produk", "Barcode", "Harga", "Jumlah", "Subtotal", "Tanggal Transaksi"
    });

    try {
        SimpleDateFormat sdfTampil = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String sql = "SELECT p.id_penjualan, u.username, pr.id_produk, pr.nama_produk, pr.barcode, " +
                     "dp.harga_jual, dp.jumlah, dp.subtotal, p.tanggal_transaksi " +
                     "FROM penjualan p " +
                     "JOIN pengguna u ON p.id_pengguna = u.id_pengguna " +
                     "JOIN detail_penjualan dp ON p.id_penjualan = dp.id_penjualan " +
                     "JOIN produk pr ON dp.id_produk = pr.id_produk " +
                     "WHERE pr.nama_produk LIKE ? OR pr.barcode LIKE ? OR pr.id_produk LIKE ? " +
                     "ORDER BY p.tanggal_transaksi ASC";

        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%" + keyword + "%");
        ps.setString(2, "%" + keyword + "%");
        ps.setString(3, "%" + keyword + "%");

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("id_penjualan"),
                rs.getString("username"),
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getString("barcode"),
                rs.getDouble("harga_jual"),
                rs.getInt("jumlah"),
                rs.getDouble("subtotal"),
                sdfTampil.format(rs.getTimestamp("tanggal_transaksi"))
            };
            model.addRow(row);
        }

        penjualan.setModel(model);
        sesuaikanLebarKolom(penjualan);

        rs.close();
        ps.close();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data penjualan (pencarian): " + e.getMessage());
    }
}
    
    
    
private void tampilkanDataPembelianDenganPencarian(String keyword) {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "ID Pembelian", "Nama Kasir", "ID Produk", "Nama Produk", "Jumlah", "Harga Beli", "Subtotal", "Tanggal Pembelian"
    });

    try {
        SimpleDateFormat sdfTampil = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String sql = "SELECT p.id_pembelian, u.username, pr.id_produk, pr.nama_produk, " +
                     "dp.jumlah, dp.harga_beli, dp.subtotal, p.tanggal_pembelian " +
                     "FROM pembelian p " +
                     "JOIN pengguna u ON p.id_pengguna = u.id_pengguna " +
                     "JOIN detail_pembelian dp ON p.id_pembelian = dp.id_pembelian " +
                     "JOIN produk pr ON dp.id_produk = pr.id_produk " +
                     "WHERE pr.nama_produk LIKE ? OR pr.barcode LIKE ? OR pr.id_produk LIKE ? " +
                     "ORDER BY p.tanggal_pembelian ASC";

        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%" + keyword + "%");
        ps.setString(2, "%" + keyword + "%");
        ps.setString(3, "%" + keyword + "%");

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("id_pembelian"),
                rs.getString("username"),
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getInt("jumlah"),
                rs.getDouble("harga_beli"),
                rs.getDouble("subtotal"),
                sdfTampil.format(rs.getTimestamp("tanggal_pembelian"))
            };
            model.addRow(row);
        }

        pembelian.setModel(model);
        sesuaikanLebarKolom(pembelian);

        rs.close();
        ps.close();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data pembelian (pencarian): " + e.getMessage());
    }
}

private void tampilkanDataBarangRusakDenganPencarian(String keyword) {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "ID Rusak", "ID Produk", "Nama Produk", "Jumlah", "Alasan", "Tanggal Rusak"
    });

    try {
        SimpleDateFormat sdfTampil = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String sql = "SELECT br.id_rusak, br.id_produk, pr.nama_produk, br.jumlah, br.alasan, br.tanggal_rusak " +
                     "FROM barang_rusak br " +
                     "JOIN produk pr ON br.id_produk = pr.id_produk " +
                     "WHERE pr.nama_produk LIKE ? OR pr.barcode LIKE ? OR pr.id_produk LIKE ? " +
                     "ORDER BY br.tanggal_rusak ASC";

        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%" + keyword + "%");
        ps.setString(2, "%" + keyword + "%");
        ps.setString(3, "%" + keyword + "%");

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("id_rusak"),
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getInt("jumlah"),
                rs.getString("alasan"),
                sdfTampil.format(rs.getTimestamp("tanggal_rusak"))
            };
            model.addRow(row);
        }

        barangRusak.setModel(model);
        sesuaikanLebarKolom(barangRusak);

        rs.close();
        ps.close();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data barang rusak (pencarian): " + e.getMessage());
    }
}


private void tampilkanDataReturnDenganPencarian(String keyword) {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "ID Return", "ID Pembelian", "ID Produk", "Nama Produk", "Jumlah", "Alasan", "Tanggal Return"
    });

    try {
        SimpleDateFormat sdfTampil = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String sql = "SELECT r.id_retur, r.id_pembelian, r.id_produk, p.nama_produk, r.jumlah, r.alasan, r.tanggal_return " +
                     "FROM return_pembelian r " +
                     "JOIN produk p ON r.id_produk = p.id_produk " +
                     "WHERE p.nama_produk LIKE ? OR p.barcode LIKE ? OR p.id_produk LIKE ? " +
                     "ORDER BY r.tanggal_return ASC";

        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%" + keyword + "%");
        ps.setString(2, "%" + keyword + "%");
        ps.setString(3, "%" + keyword + "%");

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("id_retur"),
                rs.getString("id_pembelian"),
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getInt("jumlah"),
                rs.getString("alasan"),
                sdfTampil.format(rs.getTimestamp("tanggal_return"))
            };
            model.addRow(row);
        }

        pengembalian.setModel(model);
        sesuaikanLebarKolom(pengembalian);

        rs.close();
        ps.close();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data return (pencarian): " + e.getMessage());
    }
}

}
    
    
    














