package tokkoku;
import database.dbtokko;
import support.KartuPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JFrame;
import support.SecurityUtil;
/**
 *
 * @author Yiung Za
 */
public class Manajemen_karyawan_Owner extends javax.swing.JFrame {
            private int x = 210;
//            JPanel activePanel = null;

    /**
     * Creates new form dbAdmin
     */
    public Manajemen_karyawan_Owner() {
        initComponents();
          btn_manajemenKaryawanan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_laporan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_manajemenKaryawanan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_laporan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_laporan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btnRfid.setBackground(new java.awt.Color(255, 255, 255, 0));

          menambahRfid.setLocationRelativeTo(null);
          dataKaryawan.setLocationRelativeTo(null);
          menambahkanAkun.setLocationRelativeTo(null);
          tampilkanPengguna();
          
          
btnCard.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        String kodeRFID = "RF" + (int)(Math.random() * 1000000);
        iptRfid.setText(kodeRFID);

        pnlCard.removeAll();

        KartuPanel kartu = new KartuPanel("src/gambar/kartu_template.png");
        kartu.setPreferredSize(new Dimension(pnlCard.getWidth(), pnlCard.getHeight()));
        kartu.setKodeRFID(kodeRFID);

        pnlCard.setLayout(new BorderLayout());
        pnlCard.add(kartu, BorderLayout.CENTER);
        pnlCard.revalidate();
        pnlCard.repaint();
    }
});



btnPrint.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        BufferedImage image = new BufferedImage(pnlCard.getWidth(), pnlCard.getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        pnlCard.paint(g2);
        g2.dispose();

        try {
            ImageIO.write(image, "png", new File("kartu_rfid.png"));
            JOptionPane.showMessageDialog(null, "Kartu berhasil disimpan sebagai kartu_rfid.png");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
});


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menambahRfid = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        iptRfid = new javax.swing.JTextField();
        pnlCard = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnCard = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        dataRPengguna = new javax.swing.JScrollPane();
        tbrPengguna = new javax.swing.JTable();
        menambahkanAkun = new javax.swing.JDialog();
        ipt_username = new javax.swing.JTextField();
        ipt_password = new javax.swing.JPasswordField();
        ComboDaftar = new javax.swing.JComboBox<>();
        btn_submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataKaryawan = new javax.swing.JDialog();
        dataRPengguna1 = new javax.swing.JScrollPane();
        tbrPengguna1 = new javax.swing.JTable();
        btn_hapusAkun = new javax.swing.JButton();
        btn_menambahAkun1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRfid = new javax.swing.JButton();
        btn_manajemenKaryawanan = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_dataPengguna = new javax.swing.JButton();
        backgroundUtama = new javax.swing.JLabel();

        menambahRfid.setTitle("Menambahkan RFID");
        menambahRfid.setBackground(new java.awt.Color(255, 255, 255));
        menambahRfid.setSize(new java.awt.Dimension(800, 600));
        menambahRfid.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setText("Membuat RFID");
        menambahRfid.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        menambahRfid.getContentPane().add(iptRfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 210, 40));

        pnlCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlCard.setForeground(new java.awt.Color(255, 255, 255));
        menambahRfid.getContentPane().add(pnlCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 410, 140));

        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        menambahRfid.getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 110, -1));

        btnCard.setText("Buat Kartu");
        menambahRfid.getContentPane().add(btnCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        btnPrint.setText("Print");
        menambahRfid.getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        tbrPengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Role", "RFID"
            }
        ));
        dataRPengguna.setViewportView(tbrPengguna);

        menambahRfid.getContentPane().add(dataRPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 410, 150));

        menambahkanAkun.setSize(new java.awt.Dimension(700, 500));
        menambahkanAkun.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ipt_username.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ipt_username.setBorder(null);
        menambahkanAkun.getContentPane().add(ipt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 360, 40));

        ipt_password.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ipt_password.setBorder(null);
        ipt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipt_passwordActionPerformed(evt);
            }
        });
        menambahkanAkun.getContentPane().add(ipt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 360, 40));

        ComboDaftar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karyawan"}));
        ComboDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDaftarActionPerformed(evt);
            }
        });
        menambahkanAkun.getContentPane().add(ComboDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 170, 40));

        btn_submit.setText("Simpan");
        btn_submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
        });
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        menambahkanAkun.getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 150, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Password");
        menambahkanAkun.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 90, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nama pengguna");
        menambahkanAkun.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 140, 20));

        dataKaryawan.setSize(new java.awt.Dimension(800, 400));
        dataKaryawan.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbrPengguna1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama", "RFID"
            }
        ));
        dataRPengguna1.setViewportView(tbrPengguna1);

        dataKaryawan.getContentPane().add(dataRPengguna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 640, 170));

        btn_hapusAkun.setText("Hapus Akun");
        btn_hapusAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusAkunActionPerformed(evt);
            }
        });
        dataKaryawan.getContentPane().add(btn_hapusAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        btn_menambahAkun1.setText("Tambah Akun");
        btn_menambahAkun1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menambahAkun1MouseClicked(evt);
            }
        });
        btn_menambahAkun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menambahAkun1ActionPerformed(evt);
            }
        });
        dataKaryawan.getContentPane().add(btn_menambahAkun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRfid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRfidMouseClicked(evt);
            }
        });
        btnRfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRfidActionPerformed(evt);
            }
        });
        jPanel1.add(btnRfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 220, 110));

        btn_manajemenKaryawanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_manajemenKaryawananMouseClicked(evt);
            }
        });
        btn_manajemenKaryawanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manajemenKaryawananActionPerformed(evt);
            }
        });
        jPanel1.add(btn_manajemenKaryawanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 60));

        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 240, 50));

        btn_dataPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataPenggunaMouseClicked(evt);
            }
        });
        btn_dataPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataPenggunaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dataPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 230, 110));

        backgroundUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/pg-owner/Pg_Manajemen Karyawan-Owner.png"))); // NOI18N
        jPanel1.add(backgroundUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void btn_manajemenKaryawananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manajemenKaryawananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_manajemenKaryawananActionPerformed

    private void btn_manajemenKaryawananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manajemenKaryawananMouseClicked
    Dashboard_owner dashboard = new Dashboard_owner();
    dashboard.setExtendedState(JFrame.MAXIMIZED_BOTH);
    dashboard.setVisible(true);
    dispose();
    System.out.println("Sekarang Berada Di Page Dashboard");
    }//GEN-LAST:event_btn_manajemenKaryawananMouseClicked

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
    Laporan_Owner laporan = new Laporan_Owner();
    laporan.setExtendedState(JFrame.MAXIMIZED_BOTH);
    laporan.setVisible(true);
    dispose();
    System.out.println("Sekarang Berada Di Page Laporan");
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btnRfidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRfidMouseClicked
        // TODO add your handling code here:
menambahRfid.setVisible(true);
    }//GEN-LAST:event_btnRfidMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
btnSimpan.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        int baris = tbrPengguna.getSelectedRow();

        if (baris == -1) {
            JOptionPane.showMessageDialog(null, "Pilih dulu baris pengguna pada tabel.");
            return;
        }

        String rfid = iptRfid.getText();
        if (rfid.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode RFID belum tersedia.");
            return;
        }

        // Ambil ID pengguna dari list berdasarkan index baris yang dipilih
        String idPengguna = idPenggunaList.get(baris);

        try {
            Connection conn = dbtokko.configDB();
            String sql = "UPDATE pengguna SET rfid = ? WHERE id_pengguna = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, rfid);
            ps.setString(2, idPengguna);

            int hasil = ps.executeUpdate();

            if (hasil > 0) {
                JOptionPane.showMessageDialog(null, "RFID berhasil disimpan ke pengguna ID: " + idPengguna);
                tampilkanPengguna();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan RFID.");
            }

            ps.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
        }
    }
});
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnRfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRfidActionPerformed

    private void ComboDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboDaftarActionPerformed

    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_submitMouseClicked

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
String username = ipt_username.getText().trim();
String password = new String(ipt_password.getPassword()).trim();
String role = ComboDaftar.getSelectedItem().toString().trim();

if (!role.equalsIgnoreCase("Karyawan")) {
    JOptionPane.showMessageDialog(this, "Pendaftaran hanya diizinkan untuk role Karyawan", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}

if (username.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Username wajib diisi", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}
if (password.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Password wajib diisi", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}
if (username.length() < 3) {
    JOptionPane.showMessageDialog(this, "Username minimal 3 karakter", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}
if (password.length() < 6) {
    JOptionPane.showMessageDialog(this, "Password minimal 6 karakter", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}
if (!password.matches("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).+$")) {
    JOptionPane.showMessageDialog(this, "Password harus mengandung huruf besar, kecil, dan angka", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}

try (Connection conn = dbtokko.configDB()) {
    // Cek username apakah sudah digunakan
    String checkUserSql = "SELECT * FROM pengguna WHERE username = ?";
    try (PreparedStatement checkStmt = conn.prepareStatement(checkUserSql)) {
        checkStmt.setString(1, username);
        ResultSet rs = checkStmt.executeQuery();
        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Username sudah digunakan", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }

    String hashedPassword = SecurityUtil.hashPassword(password);
    if (hashedPassword == null) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan pada proses hashing password.", "Gagal Registrasi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String insertSql = "INSERT INTO pengguna (username, password, role) VALUES (?, ?, ?)";
    try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
        insertStmt.setString(1, username);
        insertStmt.setString(2, hashedPassword);
        insertStmt.setString(3, role);

        int rowsInserted = insertStmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Akun berhasil dibuat!");
            ipt_username.setText("");
            ipt_password.setText("");
            tampilkanPengguna();
        } else {
            JOptionPane.showMessageDialog(this, "Registrasi gagal. Coba lagi.", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
        }
    }

} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_dataPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dataPenggunaActionPerformed

    private void btn_hapusAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusAkunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapusAkunActionPerformed

    private void btn_menambahAkun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menambahAkun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menambahAkun1ActionPerformed

    private void btn_dataPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataPenggunaMouseClicked
        // TODO add your handling code here:
        dataKaryawan.setVisible(true);
    }//GEN-LAST:event_btn_dataPenggunaMouseClicked

    private void btn_menambahAkun1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menambahAkun1MouseClicked
        // TODO add your handling code here:
        menambahkanAkun.setVisible(true); 
    }//GEN-LAST:event_btn_menambahAkun1MouseClicked

    private void ipt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipt_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manajemen_karyawan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manajemen_karyawan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manajemen_karyawan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manajemen_karyawan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manajemen_karyawan_Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboDaftar;
    private javax.swing.JLabel backgroundUtama;
    private javax.swing.JButton btnCard;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRfid;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btn_dataPengguna;
    private javax.swing.JButton btn_hapusAkun;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_manajemenKaryawanan;
    private javax.swing.JButton btn_menambahAkun1;
    private javax.swing.JButton btn_submit;
    private javax.swing.JDialog dataKaryawan;
    private javax.swing.JScrollPane dataRPengguna;
    private javax.swing.JScrollPane dataRPengguna1;
    private javax.swing.JTextField iptRfid;
    private javax.swing.JPasswordField ipt_password;
    private javax.swing.JTextField ipt_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDialog menambahRfid;
    private javax.swing.JDialog menambahkanAkun;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JTable tbrPengguna;
    private javax.swing.JTable tbrPengguna1;
    // End of variables declaration//GEN-END:variables
private List<String> idPenggunaList = new ArrayList<>();

private void tampilkanPengguna() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nama");
    model.addColumn("Role");
    model.addColumn("RFID");
    idPenggunaList.clear();

    String sql = "SELECT id_pengguna, username, role, rfid FROM pengguna";

    try {
        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "Tidak ada data pengguna.");
        } else {
            do {
                String idPengguna = rs.getString("id_pengguna");
                String username = rs.getString("username");
                String role = rs.getString("role");
                String rfid = rs.getString("rfid");

                idPenggunaList.add(idPengguna);

                model.addRow(new Object[] { username, role, rfid });
            } while (rs.next());
        }
        tbrPengguna.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}

//private void tampilkanRfid() {
//    // Membuat model tabel dengan kolom yang diinginkan
//    DefaultTableModel model = new DefaultTableModel();
//    model.addColumn("ID Pengguna");
//    model.addColumn("Nama");
//    model.addColumn("Role");
//    model.addColumn("RFID");
//
//    // Query untuk mengambil data pengguna dengan role 'Admin%'
//    String sql = "SELECT id_pengguna, username, role, rfid FROM pengguna WHERE role LIKE 'Admin%'";
//
//    try {
//        Connection conn = dbtokko.configDB(); // Menggunakan koneksi yang sudah tersedia
//        PreparedStatement ps = conn.prepareStatement(sql);
//        ResultSet rs = ps.executeQuery();
//
//        // Cek apakah ada hasil
//        if (!rs.isBeforeFirst()) {
//            JOptionPane.showMessageDialog(this, "Tidak ada pengguna dengan role 'Admin'.");
//        } else {
//            while (rs.next()) {
//                model.addRow(new Object[] {
//                    rs.getString("id_pengguna"),
//                    rs.getString("username"),
//                    rs.getString("role"),
//                    rs.getString("rfid")
//                });
//            }
//        }
//
//        tbrPengguna.setModel(model);
//    } catch (SQLException e) {
//        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
//    }
//}


}


