package tokkoku;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.common.BitMatrix;
import database.dbtokko;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.image.BufferedImage;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NINDY
 */
public class Menambah_dataBarang extends javax.swing.JFrame {
        
    private String selectedIdProduk;

    public Menambah_dataBarang() {
        initComponents();
        pnUbahh.setVisible(false);
        tblData.addMouseListener(new MouseAdapter() {});
        tblData.addMouseMotionListener(new MouseMotionAdapter() {});
        JTable tblStokProduk = new JTable();
        SpinnerNumberModel model = new SpinnerNumberModel(1, 0, 9999, 1);
        SpnJumlah.setModel(model);
        loadDataProduk();
        pnTambahBarcodesee.setLocationRelativeTo(null);
        btnTambahh.setLocationRelativeTo(null);
        pnUbahh.setLocationRelativeTo(null);
        pnlRusakk.setLocationRelativeTo(null);
        pnl_barangrusakk.setLocationRelativeTo(null);
        
        btn_dashboard.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_penjualan.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_pembelian.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_pemasok.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_pengembalian.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_riwayat.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_logout.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        
btnBarangRusak.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        int selectedRow = tblData.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Silakan pilih salah satu item dari tabel produk.");
            return;
        }

        try {
            String idProduk = tblData.getValueAt(selectedRow, 0).toString();
            tampilkanStokProduk(idProduk);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal membaca ID produk: " + ex.getMessage());
        }
    }
});


btn_rusak.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        int selectedRow = dataStok.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih item dari tabel stok terlebih dahulu.");
            return;
        }

        try {
            String idProduk = dataStok.getValueAt(selectedRow, 0).toString();

            pnlRusakk.setVisible(true);
            pnlRusakk.setEnabled(true);

            jtId.setText(idProduk);
            jtId.setEditable(false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal memproses: " + ex.getMessage());
        }
    }
});

dataStok.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        int row = dataStok.getSelectedRow();
        if (row != -1) {
            String idStok = dataStok.getValueAt(row, 1).toString(); // kolom ke-1 adalah ID STOK
            jtId.setText(idStok);
        }
    }
});


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTambahBarcodesee = new javax.swing.JDialog();
        showPanelBarcode = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        outputBarcode = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        btnBatal2 = new javax.swing.JButton();
        btn_simpanBarcode = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnTambahh = new javax.swing.JDialog();
        txtNamaproduk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSimpan1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnUbahh = new javax.swing.JDialog();
        txtNamaproduk1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBatal1 = new javax.swing.JButton();
        btnSimpan2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pnlRusakk = new javax.swing.JDialog();
        jCalenderMasok = new de.wannawork.jcalendar.JCalendarComboBox();
        SpnJumlah = new javax.swing.JSpinner();
        jtAlasan = new javax.swing.JComboBox<>();
        btnMasuk = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pnl_barangrusakk = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataStok = new javax.swing.JTable();
        btn_rusak = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnBarcode = new javax.swing.JButton();
        btnBarangRusak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btn_dashboard = new javax.swing.JButton();
        btn_penjualan = new javax.swing.JButton();
        btn_pembelian = new javax.swing.JButton();
        btn_pemasok = new javax.swing.JButton();
        btn_pengembalian = new javax.swing.JButton();
        btn_riwayat = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pnTambahBarcodesee.setTitle("Generate Barcode");
        pnTambahBarcodesee.setSize(new java.awt.Dimension(500, 350));
        pnTambahBarcodesee.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout showPanelBarcodeLayout = new javax.swing.GroupLayout(showPanelBarcode);
        showPanelBarcode.setLayout(showPanelBarcodeLayout);
        showPanelBarcodeLayout.setHorizontalGroup(
            showPanelBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        showPanelBarcodeLayout.setVerticalGroup(
            showPanelBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnTambahBarcodesee.getContentPane().add(showPanelBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 350, 100));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Barcode");
        pnTambahBarcodesee.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 69, -1));

        outputBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputBarcodeActionPerformed(evt);
            }
        });
        pnTambahBarcodesee.getContentPane().add(outputBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 240, 32));

        generateButton.setText("Generate");
        generateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateButtonMouseClicked(evt);
            }
        });
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });
        pnTambahBarcodesee.getContentPane().add(generateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 93, 32));

        btn_cetak.setText("Cetak");
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakMouseClicked(evt);
            }
        });
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        pnTambahBarcodesee.getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 93, 32));

        btnBatal2.setText("Batal");
        btnBatal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal2ActionPerformed(evt);
            }
        });
        pnTambahBarcodesee.getContentPane().add(btnBatal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 112, 30));

        btn_simpanBarcode.setText("Simpan");
        btn_simpanBarcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanBarcodeMouseClicked(evt);
            }
        });
        btn_simpanBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanBarcodeActionPerformed(evt);
            }
        });
        pnTambahBarcodesee.getContentPane().add(btn_simpanBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 100, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pnTambahBarcodesee.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        btnTambahh.setTitle("Tambah Barang");
        btnTambahh.setBackground(new java.awt.Color(0, 0, 255));
        btnTambahh.setSize(new java.awt.Dimension(500, 300));
        btnTambahh.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamaproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaprodukActionPerformed(evt);
            }
        });
        btnTambahh.getContentPane().add(txtNamaproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 206, 32));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Produk :");
        btnTambahh.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 111, 30));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        btnTambahh.getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 112, 42));

        btnSimpan1.setText("Simpan");
        btnSimpan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpan1MouseClicked(evt);
            }
        });
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });
        btnTambahh.getContentPane().add(btnSimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 112, 42));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        btnTambahh.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 310));

        pnUbahh.setTitle("Ubah Barang");
        pnUbahh.setSize(new java.awt.Dimension(500, 300));
        pnUbahh.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamaproduk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaproduk1ActionPerformed(evt);
            }
        });
        pnUbahh.getContentPane().add(txtNamaproduk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 206, 32));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Produk :");
        pnUbahh.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 87, 111, 30));

        btnBatal1.setText("Batal");
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });
        pnUbahh.getContentPane().add(btnBatal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 112, 42));

        btnSimpan2.setText("Simpan");
        btnSimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan2ActionPerformed(evt);
            }
        });
        pnUbahh.getContentPane().add(btnSimpan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 112, 42));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        pnUbahh.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 290));

        pnlRusakk.setTitle("Barang Rusak");
        pnlRusakk.setSize(new java.awt.Dimension(500, 500));
        pnlRusakk.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlRusakk.getContentPane().add(jCalenderMasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));
        pnlRusakk.getContentPane().add(SpnJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 82, 33));

        jtAlasan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rusak", "Kadaluarsa" }));
        pnlRusakk.getContentPane().add(jtAlasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        btnMasuk.setText("Masukkan");
        btnMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasukMouseClicked(evt);
            }
        });
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        pnlRusakk.getContentPane().add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 373, -1, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jumlah");
        pnlRusakk.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 60, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Rusak");
        pnlRusakk.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID Produk");
        pnlRusakk.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdActionPerformed(evt);
            }
        });
        pnlRusakk.getContentPane().add(jtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 50, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Alasan");
        pnlRusakk.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Barang Rusak");
        pnlRusakk.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 60));

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        pnlRusakk.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 440, 470));

        pnl_barangrusakk.setTitle("Tabel Barang Rusak");
        pnl_barangrusakk.setSize(new java.awt.Dimension(800, 650));
        pnl_barangrusakk.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Produk", "ID Stok", "Stok", "Harga Beli", "Harga Jual", "Kadaluarsa"
            }
        ));
        jScrollPane2.setViewportView(dataStok);

        pnl_barangrusakk.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 734, 470));

        btn_rusak.setText("Barang Rusak");
        btn_rusak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rusakActionPerformed(evt);
            }
        });
        pnl_barangrusakk.getContentPane().add(btn_rusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 132, 42));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        pnl_barangrusakk.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 640));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTambah.setContentAreaFilled(false);
        btnTambah.setBorderPainted(false);
        btnTambah.setBorder(null);
        btnTambah.setBorderPainted(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 210, 50));

        btnUbah.setContentAreaFilled(false);
        btnUbah.setBorderPainted(false);
        btnUbah.setBorder(null);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 110, 50));

        btnBarcode.setContentAreaFilled(false);
        btnBarcode.setBorderPainted(false);
        btnBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarcodeActionPerformed(evt);
            }
        });
        getContentPane().add(btnBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 140, 50));

        btnBarangRusak.setContentAreaFilled(false);
        btnBarangRusak.setBorderPainted(false);
        btnBarangRusak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBarangRusakMouseClicked(evt);
            }
        });
        btnBarangRusak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangRusakActionPerformed(evt);
            }
        });
        getContentPane().add(btnBarangRusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 220, 50));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Barcode", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 1120, 570));

        btn_dashboard.setBorder(null);
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
        });
        getContentPane().add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 40));

        btn_penjualan.setBorder(null);
        btn_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 50));

        btn_pembelian.setBorder(null);
        btn_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseClicked(evt);
            }
        });
        btn_pembelian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_pembelianKeyPressed(evt);
            }
        });
        getContentPane().add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 40));

        btn_pemasok.setBorder(null);
        btn_pemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pemasokMouseClicked(evt);
            }
        });
        getContentPane().add(btn_pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 240, 40));

        btn_pengembalian.setBorder(null);
        btn_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseClicked(evt);
            }
        });
        getContentPane().add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 240, 50));

        btn_riwayat.setBorder(null);
        btn_riwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_riwayatMouseClicked(evt);
            }
        });
        getContentPane().add(btn_riwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 240, 50));

        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Pg_Tambah Data Barang-Karyawan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        btnTambahh.setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBarangRusakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangRusakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarangRusakActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
int row = tblData.getSelectedRow();
if (row != -1) {

    pnUbahh.setVisible(true);

    String idProduk = tblData.getValueAt(row, 0).toString();
    String namaProduk = tblData.getValueAt(row, 1).toString();

    txtNamaproduk1.setText(namaProduk);


    this.selectedIdProduk = idProduk;

} else {
    JOptionPane.showMessageDialog(null, "Pilih dahulu data yang ingin diubah.");
}


    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarcodeActionPerformed
        
     int row = tblData.getSelectedRow();
        if (row != -1) {
        pnTambahBarcodesee.setVisible(true);
        }

   
    }//GEN-LAST:event_btnBarcodeActionPerformed

    private void txtNamaproduk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaproduk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaproduk1ActionPerformed

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        pnUbahh.setVisible(false);
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnSimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan2ActionPerformed

String namaProduk = txtNamaproduk1.getText().trim();

if (namaProduk.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Nama produk tidak boleh kosong.");
    return;
}


String sqlUpdate = "UPDATE produk SET nama_produk = ? WHERE id_produk = ?";
try (
    Connection conn = dbtokko.configDB();
    PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
) {
    psUpdate.setString(1, namaProduk);
    psUpdate.setString(2, selectedIdProduk); // ← gunakan ID yang sudah disimpan

    int updated = psUpdate.executeUpdate();
    if (updated > 0) {
        JOptionPane.showMessageDialog(null, "Data produk berhasil diubah.");

    
        txtNamaproduk1.setText("");

       
//       pnUbah.setVisible(false);

     
        loadDataProduk(); // ← Buat method untuk ambil ulang data produk
    } else {
        JOptionPane.showMessageDialog(null, "Data gagal diubah.");
    }
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
}

    }//GEN-LAST:event_btnSimpan2ActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
String sqlGetLastId = "SELECT id_produk FROM produk ORDER BY id_produk DESC LIMIT 1";
String sqlInsert = "INSERT INTO produk (id_produk, nama_produk) VALUES (?, ?)";
String sqlSelectAll = "SELECT id_produk, nama_produk, barcode FROM produk";

try (
    Connection conn = dbtokko.configDB();
    PreparedStatement psGetLastId = conn.prepareStatement(sqlGetLastId);
    PreparedStatement psInsert = conn.prepareStatement(sqlInsert);
    PreparedStatement psSelectAll = conn.prepareStatement(sqlSelectAll);
) {
    String namaProduk = txtNamaproduk.getText().trim();

    if (namaProduk.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nama produk tidak boleh kosong.");
        return;
    }

   
    String newId = "P001";
    try (ResultSet rs = psGetLastId.executeQuery()) {
        if (rs.next()) {
            String lastId = rs.getString("id_produk");
            int number = Integer.parseInt(lastId.substring(1)) + 1;
            newId = String.format("P%03d", number);
        }
    }

    
    psInsert.setString(1, newId);
    psInsert.setString(2, namaProduk);
    psInsert.executeUpdate();

  
    JOptionPane.showMessageDialog(null, "Data produk berhasil disimpan.");
    txtNamaproduk.setText("");

   
    try (ResultSet rsAll = psSelectAll.executeQuery()) {
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.setRowCount(0);

        while (rsAll.next()) {
            String idProduk = rsAll.getString("id_produk");
            String nama = rsAll.getString("nama_produk");
            String barcode = rsAll.getString("barcode");
            model.addRow(new Object[]{idProduk, nama, barcode});
        }
    }

    
    loadDataProduk();

} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
}



    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
btnTambahh.setVisible(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtNamaprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaprodukActionPerformed

    private void btnSimpan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpan1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpan1MouseClicked

    private void btnBarangRusakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangRusakMouseClicked
        // TODO add your handling code here:
        pnl_barangrusakk.setVisible(true);
    }//GEN-LAST:event_btnBarangRusakMouseClicked

    private void btn_rusakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rusakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_rusakActionPerformed

    private void jtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdActionPerformed

    private void btnMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukMouseClicked
        // TODO add your handling code here:
btnMasuk.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        Connection conn = null;

        try {
            String idStok = jtId.getText().trim();
            String alasan = jtAlasan.getSelectedItem() != null ? jtAlasan.getSelectedItem().toString() : "";
            java.util.Date tanggalRusakUtil = jCalenderMasok.getDate();
            int jumlahRusak = (int) SpnJumlah.getValue();

            if (idStok.isEmpty() || alasan.isEmpty() || tanggalRusakUtil == null || jumlahRusak <= 0) {
                JOptionPane.showMessageDialog(null, "Lengkapi semua data terlebih dahulu.");
                return;
            }

            java.sql.Date tanggalRusakSQL = new java.sql.Date(tanggalRusakUtil.getTime());

            conn = dbtokko.configDB();
            conn.setAutoCommit(false);

            String idProduk = "";
            String sqlGetProduk = "SELECT id_produk, stok FROM stok_produk WHERE id_stok = ?";
            int stokTersedia = 0;

            try (PreparedStatement ps = conn.prepareStatement(sqlGetProduk)) {
                ps.setString(1, idStok);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        idProduk = rs.getString("id_produk");
                        stokTersedia = rs.getInt("stok");
                    } else {
                        JOptionPane.showMessageDialog(null, "ID Stok tidak ditemukan di stok_produk.");
                        conn.rollback();
                        return;
                    }
                }
            }

            if (stokTersedia < jumlahRusak) {
                JOptionPane.showMessageDialog(null, "Stok tidak mencukupi. Tersedia: " + stokTersedia);
                conn.rollback();
                return;
            }

            String sqlInsert = "INSERT INTO barang_rusak (id_produk, alasan, tanggal_rusak, jumlah) VALUES (?, ?, ?, ?)";
            try (PreparedStatement psInsert = conn.prepareStatement(sqlInsert)) {
                psInsert.setString(1, idProduk);
                psInsert.setString(2, alasan);
                psInsert.setDate(3, tanggalRusakSQL);
                psInsert.setInt(4, jumlahRusak);

                if (psInsert.executeUpdate() == 0) {
                    JOptionPane.showMessageDialog(null, "Gagal menyimpan ke barang_rusak.");
                    conn.rollback();
                    return;
                }
            }

            String sqlUpdate = "UPDATE stok_produk SET stok = stok - ? WHERE id_stok = ?";
            try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                psUpdate.setInt(1, jumlahRusak);
                psUpdate.setString(2, idStok);

                if (psUpdate.executeUpdate() == 0) {
                    JOptionPane.showMessageDialog(null, "Gagal mengurangi stok.");
                    conn.rollback();
                    return;
                }
            }

            conn.commit();
            JOptionPane.showMessageDialog(null, "Barang rusak berhasil dicatat.");
            pnlRusakk.setVisible(false);
            loadDataProduk();
            tampilkanStokProduk(idProduk);
        } catch (Exception ex) {
            ex.printStackTrace();
            try {
                if (conn != null) conn.rollback();
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.setAutoCommit(true);
                    conn.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
});



    }//GEN-LAST:event_btnMasukMouseClicked

    private void btn_simpanBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanBarcodeActionPerformed

    private void btn_simpanBarcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanBarcodeMouseClicked
        // TODO add your handling code here:
        String barcode = outputBarcode.getText().trim();

        if (barcode.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Barcode tidak boleh kosong.");
            return;
        }

        int row = tblData.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data produk terlebih dahulu di tabel.");
            return;
        }

        String idProduk = tblData.getValueAt(row, 0).toString();

        String sqlUpdate = "UPDATE produk SET barcode = ? WHERE id_produk = ?";

        try (
            Connection conn = dbtokko.configDB();
            PreparedStatement ps = conn.prepareStatement(sqlUpdate);
        ) {
            ps.setString(1, barcode);
            ps.setString(2, idProduk);

            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Barcode berhasil disimpan.");
                outputBarcode.setText("");
                // Bersihkan panel barcode setelah simpan
                showPanelBarcode.removeAll();
                showPanelBarcode.revalidate();
                showPanelBarcode.repaint();

                loadDataProduk();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan barcode.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanBarcodeMouseClicked

    private void btnBatal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal2ActionPerformed
        pnTambahBarcodesee.setVisible(false);
    }//GEN-LAST:event_btnBatal2ActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void btn_cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseClicked
        // TODO add your handling code here:
        btn_cetak.addActionListener(e -> {
            try {
                String kode = outputBarcode.getText();
                if (kode == null || kode.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Barcode belum dibuat!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                BitMatrix matrix = new MultiFormatWriter().encode(
                    kode, BarcodeFormat.CODE_128, 300, 100
                );

                int width = matrix.getWidth();
                int height = matrix.getHeight();
                BufferedImage image = new BufferedImage(width, height + 30, BufferedImage.TYPE_INT_RGB);
                Graphics2D g = image.createGraphics();

                g.setColor(Color.WHITE);
                g.fillRect(0, 0, width, height + 30);

                g.setColor(Color.BLACK);
                for (int y = 0; y < height; y++) {
                    for (int x = 0; x < width; x++) {
                        if (matrix.get(x, y)) {
                            g.fillRect(x, y, 1, 1);
                        }
                    }
                }

                g.setFont(new Font("Arial", Font.PLAIN, 20));
                FontMetrics fontMetrics = g.getFontMetrics();
                int textWidth = fontMetrics.stringWidth(kode);
                int xText = (width - textWidth) / 2;
                int yText = height + 20;
                g.drawString(kode, xText, yText);
                g.dispose();

                String folder = "barcodes/";
                File folderDir = new File(folder);
                if (!folderDir.exists()) {
                    folderDir.mkdirs();
                }

                File outputFile = new File(folder + kode + ".png");
                ImageIO.write(image, "PNG", outputFile);

                PrinterJob job = PrinterJob.getPrinterJob();
                job.setJobName("Cetak Barcode");

                job.setPrintable((graphics, pageFormat, pageIndex) -> {
                    if (pageIndex > 0) return Printable.NO_SUCH_PAGE;

                    Graphics2D g2d = (Graphics2D) graphics;
                    g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                    g2d.drawImage(image, 100, 100, null);
                    return Printable.PAGE_EXISTS;
                });

                boolean doPrint = job.printDialog(); // Tampilkan dialog printer
                if (doPrint) {
                    job.print();
                }

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null,
                    "Gagal mencetak barcode", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }//GEN-LAST:event_btn_cetakMouseClicked

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateButtonActionPerformed

    private void generateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateButtonMouseClicked
        // TODO add your handling code here:
        try {

            StringBuilder kode = new StringBuilder();
            for (int i = 0; i < 13; i++) {
                kode.append((int)(Math.random() * 10));
            }

            outputBarcode.setText(kode.toString());

            BitMatrix matrix = new MultiFormatWriter().encode(
                kode.toString(), BarcodeFormat.CODE_128, 300, 100
            );

            int width = matrix.getWidth();
            int height = matrix.getHeight();
            BufferedImage image = new BufferedImage(width, height + 30, BufferedImage.TYPE_INT_RGB);
            Graphics2D g = image.createGraphics();

            g.setColor(Color.WHITE);
            g.fillRect(0, 0, width, height + 30);

            g.setColor(Color.BLACK);
            for (int y = 0; y < height; y++) {
                for (int x = 0; x < width; x++) {
                    if (matrix.get(x, y)) {
                        g.fillRect(x, y, 1, 1);
                    }
                }
            }

            g.setFont(new Font("Arial", Font.PLAIN, 20));
            FontMetrics fontMetrics = g.getFontMetrics();
            int textWidth = fontMetrics.stringWidth(kode.toString());
            int xText = (width - textWidth) / 2;
            int yText = height + 20;
            g.drawString(kode.toString(), xText, yText);
            g.dispose();

            showPanelBarcode.removeAll();
            JLabel lbl = new JLabel(new ImageIcon(image.getScaledInstance(
                showPanelBarcode.getWidth(),
                showPanelBarcode.getHeight(),
                Image.SCALE_SMOOTH
            )));
            lbl.setHorizontalAlignment(JLabel.CENTER);
            lbl.setVerticalAlignment(JLabel.CENTER);
            showPanelBarcode.setLayout(new BorderLayout());
            showPanelBarcode.add(lbl, BorderLayout.CENTER);
            showPanelBarcode.revalidate();
            showPanelBarcode.repaint();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,
                "Gagal membuat barcode", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateButtonMouseClicked

    private void outputBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputBarcodeActionPerformed

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        // TODO add your handling code here:
        Dashboard_karyawan dashboard = new Dashboard_karyawan();
        dashboard.setVisible(true);
        dashboard.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        System.out.println("Sekarang Dalam Page Dashboard");
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseClicked
        try {
            // TODO add your handling code here:
            Penjualan_karyawan penjualan = new Penjualan_karyawan();
            penjualan.setExtendedState(JFrame.MAXIMIZED_BOTH);
            penjualan.setVisible(true);
            dispose();
            System.out.println("Sekarang Page Penjualan");
        } catch (SQLException ex) {
            Logger.getLogger(Menambah_dataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_penjualanMouseClicked

    private void btn_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseClicked
        // TODO add your handling code here:
            Pembelian_karyawan pembelian = new Pembelian_karyawan();
            pembelian.setExtendedState(JFrame.MAXIMIZED_BOTH);
            pembelian.setVisible(true);
            dispose();
            System.out.println("Sekarang Dalam Page Pembelian");
    }//GEN-LAST:event_btn_pembelianMouseClicked

    private void btn_pemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemasokMouseClicked
        // TODO add your handling code here:
            Pemasok_Karyawan pemasok = new Pemasok_Karyawan();
            pemasok.setExtendedState(JFrame.MAXIMIZED_BOTH);
            pemasok.setVisible(true);
            dispose();
            System.out.println("Sekarang Dalam Page Pemasok");
    }//GEN-LAST:event_btn_pemasokMouseClicked

    private void btn_riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_riwayatMouseClicked
        // TODO add your handling code here:
        Riwayat_karyawan laporan = new Riwayat_karyawan();
        laporan.setExtendedState(JFrame.MAXIMIZED_BOTH);
        laporan.setVisible(true);
        dispose();
        System.out.println("Sekarang Dalam Page Riwayat");
    }//GEN-LAST:event_btn_riwayatMouseClicked

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btn_pembelianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_pembelianKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pembelianKeyPressed

    private void btn_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseClicked
        // TODO add your handling code here:
        PengembalianBarang_karyawan pengembalian = new PengembalianBarang_karyawan();
        pengembalian.setExtendedState(JFrame.MAXIMIZED_BOTH);
        pengembalian.setVisible(true);
        dispose();
        System.out.println("Sekarang Dalam Page Pengembalian Barang");
    }//GEN-LAST:event_btn_pengembalianMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            null,
            "Yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setExtendedState(JFrame.MAXIMIZED_BOTH);
            login.setVisible(true);
            dispose();
            System.out.println("Anda Logout");
        } else {
            System.out.println("Logout dibatalkan");
        }
    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menambah_dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menambah_dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menambah_dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menambah_dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menambah_dataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnJumlah;
    private javax.swing.JButton btnBarangRusak;
    private javax.swing.JButton btnBarcode;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnBatal2;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JButton btnSimpan2;
    private javax.swing.JButton btnTambah;
    private javax.swing.JDialog btnTambahh;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pemasok;
    private javax.swing.JButton btn_pembelian;
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_riwayat;
    private javax.swing.JButton btn_rusak;
    private javax.swing.JButton btn_simpanBarcode;
    private javax.swing.JTable dataStok;
    private javax.swing.JButton generateButton;
    private de.wannawork.jcalendar.JCalendarComboBox jCalenderMasok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jtAlasan;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField outputBarcode;
    private javax.swing.JDialog pnTambahBarcodesee;
    private javax.swing.JDialog pnUbahh;
    private javax.swing.JDialog pnlRusakk;
    private javax.swing.JDialog pnl_barangrusakk;
    private javax.swing.JPanel showPanelBarcode;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtNamaproduk;
    private javax.swing.JTextField txtNamaproduk1;
    // End of variables declaration//GEN-END:variables
private void loadDataProduk() {
    String sql = "SELECT p.id_produk, p.nama_produk, p.barcode, IFNULL(sp.stok, 0) AS jumlah_stok " +
                 "FROM produk p " +
                 "LEFT JOIN stok_produk sp ON p.id_produk = sp.id_produk";

    try (
        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
    ) {
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID Produk", "Nama Produk", "Barcode", "Stok"}, 0
        );
        tblData.setModel(model);

        while (rs.next()) {
            String idProduk = rs.getString("id_produk");
            String namaProduk = rs.getString("nama_produk");
            String barcode = rs.getString("barcode");
            int stok = rs.getInt("jumlah_stok");

            model.addRow(new Object[]{idProduk, namaProduk, barcode, stok});
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data produk: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}



public void tampilkanStokProduk(String idProduk) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Stok");
    model.addColumn("ID Produk");
    model.addColumn("Stok");
    model.addColumn("Harga Beli");
    model.addColumn("Harga Jual");
    model.addColumn("Tanggal Kedaluwarsa");

    String sql = "SELECT id_stok, id_produk, stok, harga_beli, harga_jual, tanggal_kedaluwarsa " +
                 "FROM stok_produk WHERE id_produk = ?";

    try (Connection conn = dbtokko.configDB();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, idProduk);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_stok"),
                rs.getString("id_produk"),
                rs.getInt("stok"),
                rs.getDouble("harga_beli"),
                rs.getDouble("harga_jual"),
                rs.getDate("tanggal_kedaluwarsa")
            });
        }

        dataStok.setModel(model); // pastikan 'dataStok' adalah JTable Anda

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan stok produk: " + e.getMessage());
    }
}




}


   

   
  

