/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokkoku;
import database.dbtokko;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yiung Za
 */
public class Pemasok_Karyawan extends javax.swing.JFrame {
                private int x = 210;
    public void tampilkanDataSuplier() {
    String[] kolom = {"Nama", "Kontak", "Alamat"};
    DefaultTableModel model = new DefaultTableModel(null, kolom);

    try (Connection conn = dbtokko.getConnection()) {
        String sql = "SELECT * FROM suplier";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            String nama = rs.getString("nama");
            String kontak = rs.getString("kontak");
            String alamat = rs.getString("alamat");

            String[] data = {nama, kontak, alamat};
            model.addRow(data);
        }

        dataPemasok.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}

    /**
     * Creates new form Pemasok_master
     */
    public Pemasok_Karyawan() {
        initComponents();
        tampilkanDataSuplier();
        btn_pemasok.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_hapus.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_pembelian.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_pemasok.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_pengembalian.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_stok.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_laporan.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_dashboard.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_penjualan.setBackground(new java.awt.Color(255, 255, 255, 0));
        
        tambahPemasok.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahPemasok = new javax.swing.JDialog();
        Pemasok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ipt_nama = new javax.swing.JTextField();
        ipt_kontak = new javax.swing.JTextField();
        ipt_alamat = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataPemasok = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_hapus = new javax.swing.JButton();
        btn_pemasok = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();
        btn_penjualan = new javax.swing.JButton();
        btn_pembelian = new javax.swing.JButton();
        btn_pengembalian = new javax.swing.JButton();
        btn_stok = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        backgroundUtama = new javax.swing.JLabel();

        tambahPemasok.setTitle("Menambah Data Pemasok");
        tambahPemasok.setSize(new java.awt.Dimension(450, 400));
        tambahPemasok.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pemasok.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Pemasok.setText("Pemasok");
        tambahPemasok.getContentPane().add(Pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Alamat");
        tambahPemasok.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nama");
        tambahPemasok.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("No. Hp");
        tambahPemasok.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        ipt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipt_namaActionPerformed(evt);
            }
        });
        tambahPemasok.getContentPane().add(ipt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, 30));

        ipt_kontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipt_kontakActionPerformed(evt);
            }
        });
        tambahPemasok.getContentPane().add(ipt_kontak, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 210, 30));
        tambahPemasok.getContentPane().add(ipt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 50));

        btn_simpan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        tambahPemasok.getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataPemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NAMA", "NO. HP", "ALAMAT"
            }
        ));
        jScrollPane1.setViewportView(dataPemasok);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 1060, 530));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 90, 40));

        btn_pemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pemasokMouseClicked(evt);
            }
        });
        btn_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pemasokActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 120, 40));

        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
        });
        jPanel1.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 50));

        btn_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseClicked(evt);
            }
        });
        jPanel1.add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 50));

        btn_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseClicked(evt);
            }
        });
        jPanel1.add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 50));

        btn_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseClicked(evt);
            }
        });
        jPanel1.add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 240, 50));

        btn_stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stokMouseClicked(evt);
            }
        });
        btn_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stokActionPerformed(evt);
            }
        });
        jPanel1.add(btn_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 240, 50));

        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        jPanel1.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 240, 50));

        backgroundUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Pemasok-Karyawan.png"))); // NOI18N
        jPanel1.add(backgroundUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemasokMouseClicked
        // TODO add your handling code here:
        tambahPemasok.setVisible(true);
    }//GEN-LAST:event_btn_pemasokMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
         int selectedRow = dataPemasok.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu.");
        return;
    }

    String id = dataPemasok.getValueAt(selectedRow, 0).toString();

    int konfirmasi = JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin menghapus data ini?", 
        "Konfirmasi", JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try (Connection conn = dbtokko.getConnection()) {
            String sql = "DELETE FROM suplier WHERE nama = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, id);
            ps.executeUpdate();
            tampilkanDataSuplier();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pemasokActionPerformed

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        // TODO add your handling code here:
        Dashboard_karyawan dashboard = new Dashboard_karyawan();
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseClicked
        // TODO add your handling code here:
        Penjualan_karyawan penjualan = Penjualan_master();
        penjualan.setVisible(true);
        dispose();
        System.out.println("Sekarang Dalam Page Penjualan " + "Master");
    }//GEN-LAST:event_btn_penjualanMouseClicked

    private void btn_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseClicked
        // TODO add your handling code here:
        System.out.println("Sekarang Dalam Page Pembelian " + "Master");
    }//GEN-LAST:event_btn_pembelianMouseClicked

    private void btn_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseClicked
        // TODO add your handling code here:

        System.out.println("Sekarang Dalam Page Pengembalian Barang " + "Master");
    }//GEN-LAST:event_btn_pengembalianMouseClicked

    private void btn_stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stokMouseClicked
        // TODO add your handling code here:
        Menambah_dataBarang stok = new Menambah_dataBarang();
        stok.setExtendedState(JFrame.MAXIMIZED_BOTH);
        stok.setVisible(true);
        dispose();
        System.out.println("Sekarang Dalam Page Stok " + "Master");
    }//GEN-LAST:event_btn_stokMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
        Pemasok_Karyawan laporan= new Pemasok_Karyawan();
        laporan.setExtendedState(JFrame.MAXIMIZED_BOTH);
        laporan.setVisible(true);
        dispose();
        System.out.println("Sekarang Dalam Page Laporan " + "Master");
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_stokActionPerformed

    private void ipt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipt_namaActionPerformed

    private void ipt_kontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipt_kontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipt_kontakActionPerformed

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        // TODO add your handling code here:
    String nama = ipt_nama.getText();
    String kontak = ipt_kontak.getText();
    String alamat = ipt_alamat.getText();

    if (nama.isEmpty() || kontak.isEmpty() || alamat.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Semua field harus diisi!");
        return;
    }

    try {
        String sql = "INSERT INTO pemasok (nama, kontak, alamat) VALUES (?, ?, ?)";
        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nama);
        ps.setString(2, kontak);
        ps.setString(3, alamat);

        int rowsInserted = ps.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            ipt_nama.setText("");
            ipt_kontak.setText("");
            ipt_alamat.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan.");
        }

        ps.close();
        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_simpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemasok_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemasok_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemasok_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemasok_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemasok_Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pemasok;
    private javax.swing.JLabel backgroundUtama;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_pemasok;
    private javax.swing.JButton btn_pembelian;
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_stok;
    private javax.swing.JTable dataPemasok;
    private javax.swing.JTextField ipt_alamat;
    private javax.swing.JTextField ipt_kontak;
    private javax.swing.JTextField ipt_nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog tambahPemasok;
    // End of variables declaration//GEN-END:variables

    private Penjualan_karyawan Penjualan_master() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
