/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokkoku;
import database.dbtokko;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.*;
import java.awt.event.*;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Yiung Za
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        ipt_username.setBackground(new java.awt.Color(255, 255, 255, 0));
        ipt_password.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_submit.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_masuk.setBackground(new java.awt.Color(255, 255, 255, 0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_submit = new javax.swing.JButton();
        ipt_username = new javax.swing.JTextField();
        ipt_password = new javax.swing.JPasswordField();
        btn_masuk = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_submit.setBorder(null);
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
        });
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 550, 140, 40));

        ipt_username.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ipt_username.setBorder(null);
        getContentPane().add(ipt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 360, 40));

        ipt_password.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ipt_password.setBorder(null);
        getContentPane().add(ipt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 360, 40));

        btn_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_masukMouseClicked(evt);
            }
        });
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        getContentPane().add(btn_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 480, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Pg_register.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
String username = ipt_username.getText().trim();
String password = new String(ipt_password.getPassword()).trim();

if (username.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Username wajib diisi", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}
if (password.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Password wajib diisi", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}

if (username.length() < 3) {
    JOptionPane.showMessageDialog(this, "Username minimal 3 karakter", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}
if (password.length() < 6) {
    JOptionPane.showMessageDialog(this, "Password minimal 6 karakter", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}

if (!password.matches("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).+$")) {
    JOptionPane.showMessageDialog(this, "Password harus mengandung huruf besar, kecil, dan angka", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}

try (Connection conn = dbtokko.configDB()) {
    String checkSql = "SELECT * FROM pengguna WHERE username = ?";
    try (PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {
        checkStmt.setString(1, username);
        ResultSet rs = checkStmt.executeQuery();
        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Username sudah digunakan", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }

    String hashedPassword = hashPassword(password);
    if (hashedPassword == null) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan pada proses hashing password.", "Gagal Registrasi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "INSERT INTO pengguna (username, password) VALUES (?, ?)";
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, username);
        stmt.setString(2, hashedPassword);

        int rowsInserted = stmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Akun berhasil dibuat!");
            this.setVisible(false);
            new Login().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Registrasi gagal. Coba lagi.", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
        }
    }

} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btn_submitActionPerformed
// Fungsi hashing password dengan SHA-256
private String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hashedBytes = md.digest(password.getBytes("UTF-8"));
        StringBuilder sb = new StringBuilder();
        for (byte b : hashedBytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    } catch (NoSuchAlgorithmException | java.io.UnsupportedEncodingException e) {
        e.printStackTrace();
        return null;
    }
}
    private void btn_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseClicked
        // TODO add your handling code here:
        Login Jlogin = new Login();
        Jlogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_masukMouseClicked

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_masukActionPerformed

    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_submitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_masuk;
    private javax.swing.JButton btn_submit;
    private javax.swing.JPasswordField ipt_password;
    private javax.swing.JTextField ipt_username;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
