/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokkoku;
import database.dbtokko;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Yiung Za
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        ipt_username.setBackground(new java.awt.Color(255, 255, 255, 0));
        ipt_password.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_show.setBackground(new java.awt.Color(255, 255, 255, 0));
        cmbRole.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_submit.setBackground(new java.awt.Color(255, 255, 255, 0));
        btn_masuk.setBackground(new java.awt.Color(255, 255, 255, 0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_submit = new javax.swing.JButton();
        ipt_username = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        ipt_password = new javax.swing.JPasswordField();
        btn_show = new javax.swing.JCheckBox();
        btn_masuk = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_submit.setBorder(null);
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
        });
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, 140, 40));

        ipt_username.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ipt_username.setBorder(null);
        getContentPane().add(ipt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 360, 40));

        cmbRole.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Master", "Admin"}));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });
        getContentPane().add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 200, 50));

        ipt_password.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ipt_password.setBorder(null);
        getContentPane().add(ipt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 365, 320, 40));

        btn_show.setFont(new java.awt.Font("Dialog", 0, 50)); // NOI18N
        btn_show.setBorder(null);
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });
        getContentPane().add(btn_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 360, 40, 50));

        btn_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_masukMouseClicked(evt);
            }
        });
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        getContentPane().add(btn_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 520, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Register (2).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
String username = ipt_username.getText().trim();
String password = new String(ipt_password.getPassword()).trim();
String role = cmbRole.getSelectedItem().toString().trim();

// Validasi input
if (username.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Username wajib diisi", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}
if (password.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Password wajib diisi", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}
if (role.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Role wajib dipilih", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}

// Validasi panjang username dan password
if (username.length() < 3) {
    JOptionPane.showMessageDialog(this, "Username minimal 3 karakter", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}
if (password.length() < 6) {
    JOptionPane.showMessageDialog(this, "Password minimal 6 karakter", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}


if (!password.matches("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).+$")) {
    JOptionPane.showMessageDialog(this, "Password harus mengandung huruf besar, kecil, dan angka", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
    return;
}


try (Connection conn = dbtokko.configDB()) {


    if (role.equalsIgnoreCase("Master")) {
        String checkMasterSql = "SELECT COUNT(*) AS master_count FROM pengguna WHERE role = 'Master'";
        try (PreparedStatement checkStmt = conn.prepareStatement(checkMasterSql)) {
            ResultSet rs = checkStmt.executeQuery();
            if (rs.next() && rs.getInt("master_count") > 0) {
                JOptionPane.showMessageDialog(this, "Anda Tidak Diberkanankan Menggunakan Role Master", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    }

    // Query untuk memasukkan data ke tabel pengguna
    String sql = "INSERT INTO pengguna (username, password, role) VALUES (?, ?, ?)";
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, username);
        stmt.setString(2, password);
        stmt.setString(3, role);

        int rowsInserted = stmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Akun Anda telah berhasil dibuat!");
            this.setVisible(false);
            Login loginFrame = new Login();
            loginFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Registrasi gagal. Coba lagi.", "Gagal Registrasi", JOptionPane.WARNING_MESSAGE);
        }
    }

} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Ada Masalah, Coba Ulangi", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btn_submitActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
        // TODO add your handling code here
        if(btn_show.isSelected()){
           ipt_password.setEchoChar((char)0);
       } else{
           ipt_password.setEchoChar('*');}
    }//GEN-LAST:event_btn_showActionPerformed

    private void btn_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseClicked
        // TODO add your handling code here:
        Login Jlogin = new Login();
        Jlogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_masukMouseClicked

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_masukActionPerformed

    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_submitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_masuk;
    private javax.swing.JCheckBox btn_show;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JPasswordField ipt_password;
    private javax.swing.JTextField ipt_username;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
