/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokkoku;
import database.dbtokko;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author Yiung Za
 */
public class Riwayat_karyawan extends javax.swing.JFrame {
            private int x = 210;
//            JPanel activePanel = null;


    public Riwayat_karyawan() {
        initComponents();
          btn_penjualan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_pembelian.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_pemasok.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_pengembalian.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_stok.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_laporan.setBackground(new java.awt.Color(255, 255, 255, 0));
          btn_dashboard.setBackground(new java.awt.Color(255, 255, 255, 0));
          
          tampilkanDataPenjualan(false, null, null);
          tampilkanDataPembelian(false, null, null);
          pembelianTbl.setVisible(false);
          
          
//JcomboBox Report
Claporan.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        String selected = (String) Claporan.getSelectedItem();
        System.out.println("Selected: " + selected);

        // Sembunyikan semua
        penjualanTbl.setVisible(false);
        pembelianTbl.setVisible(false);
        if ("Laporan Penjualan".equals(selected)) {
            penjualanTbl.setVisible(true);
        } else if ("Laporan Pembelian".equals(selected)) {
          pembelianTbl.setVisible(true);
        } else if ("Laporan Produk".equals(selected)) {
//            produkTbl.setVisible(true);
        }

        revalidate();
        repaint();
    }
});



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Claporan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JButton();
        btn_stok = new javax.swing.JButton();
        btn_pengembalian = new javax.swing.JButton();
        btn_pemasok = new javax.swing.JButton();
        btn_pembelian = new javax.swing.JButton();
        btn_penjualan = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();
        penjualanTbl = new javax.swing.JScrollPane();
        penjualan = new javax.swing.JTable();
        Jsampai = new de.wannawork.jcalendar.JCalendarComboBox();
        Jdari = new de.wannawork.jcalendar.JCalendarComboBox();
        Tampilkan = new javax.swing.JButton();
        pembelianTbl = new javax.swing.JScrollPane();
        pembelian = new javax.swing.JTable();
        backgroundUtama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Claporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laporan Penjualan", "Laporan Pembelian", "Laporan Produk", "Laporan Pengembalian Barang", "Laporan Barang Rusak"}));
        jPanel1.add(Claporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 220, 50));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("S/d");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 30, -1));

        btn_laporan.setBorder(null);
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
        });
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 240, 50));

        btn_stok.setBorder(null);
        btn_stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stokMouseClicked(evt);
            }
        });
        btn_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stokActionPerformed(evt);
            }
        });
        jPanel1.add(btn_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 240, 50));

        btn_pengembalian.setBorder(null);
        btn_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseClicked(evt);
            }
        });
        btn_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 240, 50));

        btn_pemasok.setBorder(null);
        btn_pemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pemasokMouseClicked(evt);
            }
        });
        btn_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pemasokActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 240, 50));

        btn_pembelian.setBorder(null);
        btn_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseClicked(evt);
            }
        });
        btn_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembelianActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 50));

        btn_penjualan.setBorder(null);
        btn_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseClicked(evt);
            }
        });
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 50));

        btn_dashboard.setBorder(null);
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
        });
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 50));

        penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Penjualan", "Kasir", "ID Produk", "Produk", "Barcode", "Harga", "Jumlah", "Subtotal", "Tanggal Transaksi"
            }
        ));
        penjualanTbl.setViewportView(penjualan);

        jPanel1.add(penjualanTbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 1060, 280));
        jPanel1.add(Jsampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 130, 30));
        jPanel1.add(Jdari, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 130, 30));

        Tampilkan.setText("Tampilkan");
        Tampilkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TampilkanMouseClicked(evt);
            }
        });
        jPanel1.add(Tampilkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, -1, -1));

        pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pembelian", "Nama Kasir", "ID Produk", "Nama Produk", "Jumlah", "Harga Beli", "Subtotal", "Tanggal Transaksi"
            }
        ));
        pembelianTbl.setViewportView(pembelian);

        jPanel1.add(pembelianTbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 1060, 240));

        backgroundUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Pg_laporan.png"))); // NOI18N
        jPanel1.add(backgroundUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void btn_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_stokActionPerformed

    private void btn_stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stokMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_stokMouseClicked

    private void btn_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pengembalianActionPerformed

    private void btn_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pengembalianMouseClicked

    private void btn_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pemasokActionPerformed

    private void btn_pemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemasokMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pemasokMouseClicked

    private void btn_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pembelianActionPerformed

    private void btn_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pembelianMouseClicked

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_penjualanActionPerformed

    private void btn_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_penjualanMouseClicked

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
        Dashboard_karyawan dashboard = new Dashboard_karyawan();
        dashboard.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dashboard.setVisible(true);
        dispose();
        System.out.println("Memasuki Dashboard Master");
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void TampilkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TampilkanMouseClicked
        // TODO add your handling code here:
        java.util.Date dari = Jdari.getDate();
        java.util.Date sampai = Jsampai.getDate();

        if (dari == null || sampai == null) {
        JOptionPane.showMessageDialog(null, "Silakan pilih rentang tanggal terlebih dahulu.");
        return;
        }

    tampilkanDataPenjualan(true, dari, sampai);
    }//GEN-LAST:event_TampilkanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat_karyawan().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Claporan;
    private de.wannawork.jcalendar.JCalendarComboBox Jdari;
    private de.wannawork.jcalendar.JCalendarComboBox Jsampai;
    private javax.swing.JButton Tampilkan;
    private javax.swing.JLabel backgroundUtama;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_pemasok;
    private javax.swing.JButton btn_pembelian;
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_stok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable pembelian;
    private javax.swing.JScrollPane pembelianTbl;
    private javax.swing.JTable penjualan;
    private javax.swing.JScrollPane penjualanTbl;
    // End of variables declaration//GEN-END:variables

private void tampilkanDataPenjualan(boolean filterTanggal, java.util.Date dariDate, java.util.Date sampaiDate) {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "ID Penjualan", "Kasir", "ID Produk", "Nama Produk", "Barcode", "Harga", "Jumlah", "Subtotal", "Tanggal Transaksi"
    });

    try {
        SimpleDateFormat sdfSQL = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdfTampil = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String sql = "SELECT p.id_penjualan, u.username, pr.id_produk, pr.nama_produk, pr.barcode, " +
                     "dp.harga_jual, dp.jumlah, dp.subtotal, p.tanggal_transaksi " +
                     "FROM penjualan p " +
                     "JOIN pengguna u ON p.id_pengguna = u.id_pengguna " +
                     "JOIN detail_penjualan dp ON p.id_penjualan = dp.id_penjualan " +
                     "JOIN produk pr ON dp.id_produk = pr.id_produk";

        if (filterTanggal) {
            sql += " WHERE DATE(p.tanggal_transaksi) BETWEEN ? AND ?";
        }

        sql += " ORDER BY p.tanggal_transaksi ASC";

        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);

        if (filterTanggal) {
            ps.setString(1, sdfSQL.format(dariDate));
            ps.setString(2, sdfSQL.format(sampaiDate));
        }

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("id_penjualan"),
                rs.getString("username"),
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getString("barcode"),
                rs.getDouble("harga_jual"),
                rs.getInt("jumlah"),
                rs.getDouble("subtotal"),
                sdfTampil.format(rs.getTimestamp("tanggal_transaksi"))
            };
            model.addRow(row);
        }

        penjualan.setModel(model);
        sesuaikanLebarKolom(penjualan);

        rs.close();
        ps.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data: " + e.getMessage());
    }
}

private void tampilkanDataPembelian(boolean filterTanggal, java.util.Date dariDate, java.util.Date sampaiDate) {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "ID Pembelian", "Nama Kasir", "ID Produk", "Nama Produk", "Jumlah", "Harga Beli", "Subtotal", "Tanggal Pembelian"
    });

    try {
        SimpleDateFormat sdfSQL = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdfTampil = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String sql = "SELECT p.id_pembelian, u.username, pr.id_produk, pr.nama_produk, " +
                     "dp.jumlah, dp.harga_beli, dp.subtotal, p.tanggal_pembelian " +
                     "FROM pembelian p " +
                     "JOIN pengguna u ON p.id_pengguna = u.id_pengguna " +
                     "JOIN detail_pembelian dp ON p.id_pembelian = dp.id_pembelian " +
                     "JOIN produk pr ON dp.id_produk = pr.id_produk";

        if (filterTanggal) {
            sql += " WHERE DATE(p.tanggal_pembelian) BETWEEN ? AND ?";
        }

        sql += " ORDER BY p.tanggal_pembelian ASC";

        Connection conn = dbtokko.configDB();
        PreparedStatement ps = conn.prepareStatement(sql);

        if (filterTanggal) {
            ps.setString(1, sdfSQL.format(dariDate));
            ps.setString(2, sdfSQL.format(sampaiDate));
        }

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getString("id_pembelian"),
                rs.getString("username"),
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getInt("jumlah"),
                rs.getDouble("harga_beli"),
                rs.getDouble("subtotal"),
                sdfTampil.format(rs.getTimestamp("tanggal_pembelian"))
            };
            model.addRow(row);
        }

        pembelian.setModel(model);
        sesuaikanLebarKolom(pembelian);

        rs.close();
        ps.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data pembelian: " + e.getMessage());
    }
}




























private void sesuaikanLebarKolom(JTable table) {
    final TableColumnModel columnModel = table.getColumnModel();
    for (int column = 0; column < table.getColumnCount(); column++) {
        int lebar = 15;
        for (int row = 0; row < table.getRowCount(); row++) {
            TableCellRenderer renderer = table.getCellRenderer(row, column);
            Component comp = table.prepareRenderer(renderer, row, column);
            lebar = Math.max(comp.getPreferredSize().width + 10, lebar);
        }
        if (lebar > 300)
            lebar = 300;
        columnModel.getColumn(column).setPreferredWidth(lebar);
    }
}

    private void tampilkanDataPenjualan() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}


